import { motion as Motion, useReducedMotion } from "framer-motion";
import { useLanguage } from "../../context/LanguageContext";

const resultContent = {
  pt: {
    eyebrow: "RESULTADOS QUE CHEGAM AO CAIXA",
    title: "Tecnologia só gera valor quando move o negócio.",
    description: "Sistemas, automações e experiências digitais da Tironi Tech já apoiam operações que vendem mais, capturam demanda e tomam decisões com dados reais.",
    primaryValue: "R$ 2,5 mi+",
    primaryLabel: "em faturamento mensal acompanhado nas operações de clientes",
    metrics: [
      { value: "+55%", label: "de faturamento", text: "em uma operação após a evolução da solução digital" },
      { value: "+35%", label: "de crescimento", text: "no faturamento de uma empresa após o trabalho realizado" },
      { value: "1.000+", label: "leads qualificados", text: "gerados por uma experiência digital criada para ativar demanda" },
      { value: "R$ 300 mil+", label: "em GMV", text: "movimentados por uma plataforma transacional desenvolvida sob medida" },
      { value: "R$ 200 mil", label: "em receita recorrente", text: "gerados para uma operação por uma plataforma de assinaturas desenvolvida sob medida" },
    ],
    note: "Indicadores reais de operações atendidas, apresentados de forma agregada e anonimizada.",
    cta: "Quero construir meu próximo resultado",
  },
  en: {
    eyebrow: "RESULTS THAT REACH THE BOTTOM LINE",
    title: "Technology creates value when it moves the business.",
    description: "Tironi Tech systems, automations and digital experiences support operations that sell more, capture demand and make decisions with real data.",
    primaryValue: "R$ 2.5M+", primaryLabel: "in monthly revenue tracked across client operations",
    metrics: [
      { value: "+55%", label: "revenue", text: "in one operation after the digital solution evolved" },
      { value: "+35%", label: "growth", text: "in company revenue after the delivered work" },
      { value: "1,000+", label: "qualified leads", text: "generated by a digital experience designed to activate demand" },
      { value: "R$ 300K+", label: "in GMV", text: "processed through a custom transactional platform" },
      { value: "R$ 200K", label: "in recurring revenue", text: "generated for an operation through a custom subscription platform" },
    ],
    note: "Real indicators from supported operations, shown in aggregate and anonymized form.",
    cta: "Build my next result",
  },
  es: {
    eyebrow: "RESULTADOS QUE LLEGAN A LA CAJA",
    title: "La tecnología crea valor cuando mueve el negocio.",
    description: "Los sistemas, automatizaciones y experiencias digitales de Tironi Tech apoyan operaciones que venden más, capturan demanda y deciden con datos reales.",
    primaryValue: "R$ 2,5 mi+", primaryLabel: "en facturación mensual acompañada en operaciones de clientes",
    metrics: [
      { value: "+55%", label: "de facturación", text: "en una operación después de evolucionar la solución digital" },
      { value: "+35%", label: "de crecimiento", text: "en la facturación de una empresa después del trabajo realizado" },
      { value: "1.000+", label: "leads calificados", text: "generados por una experiencia digital creada para activar demanda" },
      { value: "R$ 300 mil+", label: "en GMV", text: "movidos por una plataforma transaccional desarrollada a medida" },
      { value: "R$ 200 mil", label: "en ingresos recurrentes", text: "generados para una operación mediante una plataforma de suscripción desarrollada a medida" },
    ],
    note: "Indicadores reales de operaciones atendidas, presentados de forma agregada y anónima.",
    cta: "Construir mi próximo resultado",
  },
};

export default function BusinessResultsSection({ compact = false }) {
  const { language } = useLanguage();
  const reduceMotion = useReducedMotion();
  const content = resultContent[language] || resultContent.pt;

  return (
    <Motion.section
      className={`tt-results${compact ? " tt-results-compact" : ""}`}
      aria-labelledby="business-results-title"
      initial={reduceMotion ? false : { opacity: 0, y: 24 }}
      whileInView={reduceMotion ? undefined : { opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.18 }}
      transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}
    >
      <div className="tt-results-orbit" aria-hidden="true"><i /><i /><i /></div>
      <div className="tt-results-inner">
        <header className="tt-results-heading">
          <span>{content.eyebrow}</span>
          <h2 id="business-results-title">{content.title}</h2>
          <p>{content.description}</p>
        </header>

        <div className="tt-results-board">
          <div className="tt-results-primary">
            <small>IMPACTO ACOMPANHADO</small>
            <strong>{content.primaryValue}</strong>
            <p>{content.primaryLabel}</p>
            <span className="tt-results-pulse"><i /> DADOS DE OPERAÇÕES REAIS</span>
          </div>
          <div className="tt-results-metrics">
            {content.metrics.map((metric, index) => (
              <Motion.article key={metric.value} initial={reduceMotion ? false : { opacity: 0, scale: 0.96 }} whileInView={reduceMotion ? undefined : { opacity: 1, scale: 1 }} viewport={{ once: true, amount: 0.4 }} transition={{ duration: 0.45, delay: index * 0.06 }}>
                <span>{String(index + 1).padStart(2, "0")}</span>
                <strong>{metric.value}</strong>
                <h3>{metric.label}</h3>
                <p>{metric.text}</p>
              </Motion.article>
            ))}
          </div>
        </div>

        <footer className="tt-results-footer">
          <p>{content.note}</p>
          <a href="#contato">{content.cta}<span aria-hidden="true">↗</span></a>
        </footer>
      </div>
    </Motion.section>
  );
}
