const plans = [
  ['Club Essencial', 'R$ 4.900/mês', 'Clareza, prioridades e execução em uma frente crítica do negócio.', 'Empresa que já opera e vende, mas precisa organizar processos, indicadores e as primeiras melhorias.'],
  ['Club Growth', 'R$ 8.900/mês', 'Acompanhamento ativo de múltiplas frentes, com dados, processos, automação e ferramentas integradas.', 'Empresa em crescimento, com operação comercial e administrativa ativa e gargalos recorrentes.'],
  ['Club Partner', 'a partir de R$ 14.900/mês', 'A Tironi como extensão contínua da gestão e da tecnologia, com maior profundidade e prioridade de execução.', 'PME mais estruturada, que precisa de um parceiro recorrente em vez de vários fornecedores.'],
];

export const clubContent = {
  pt: {
    eyebrow: 'TRANSFORMAÇÃO CONTÍNUA',
    title: ['O Club entra', 'na operação', 'e faz a mudança acontecer.'],
    description: 'Diagnóstico, prioridades, implementação e acompanhamento mensal. Automação, inteligência artificial, software sob medida e ferramentas próprias entram quando aceleram o resultado — não como um pacote comprado antes de entender o problema.',
    cta: 'Quero mapear minha empresa',
    secondary: 'Conhecer como funciona',
    note: 'O diagnóstico define a frente prioritária. Projetos grandes e dedicação extraordinária seguem com escopo próprio.',
    message: 'Olá! Quero mapear minha empresa e entender se o Tironi Tech Club faz sentido.',
    member: 'PARCEIRO CONTÍNUO',
    card: 'Analisar. Implementar. Acompanhar.',
    connection: 'Um parceiro para a operação, não mais um fornecedor de ferramenta.',
    benefits: [
      ['Diagnóstico', 'Clareza sobre onde a operação perde tempo, dinheiro ou controle.'],
      ['Prioridades', 'Uma frente crítica por vez, orientada por dados e pelo impacto no negócio.'],
      ['Implementação', 'A mudança sai do papel: processo, automação, integração ou software.'],
      ['Acompanhamento', 'Indicadores revisados mês a mês, com a próxima prioridade já visível.'],
      ['Tecnologia como meio', 'IA, automação e software entram quando aceleram o resultado.'],
      ['Menos fragmentação', 'Estratégia, dados e execução trabalhando na mesma direção.'],
    ],
    outcomes: ['Priorizar', 'Executar', 'Medir', 'Evoluir'],
    plansTitle: 'Planos por envolvimento',
    plansIntro: 'O que muda de um plano para outro é a profundidade, a quantidade de frentes e a prioridade de execução.',
    plansNote: 'A capacidade de execução continua existindo para proteger a entrega. Ela deixa de ser o que o comercial compara. Projetos especiais entram em escopo à parte.',
    plansHeaders: ['Plano', 'Referência', 'O que você compra', 'Para quem'],
    plans,
  },
  en: {
    eyebrow: 'CONTINUOUS TRANSFORMATION',
    title: ['The Club steps', 'into the operation', 'and makes the change happen.'],
    description: 'Diagnosis, priorities, implementation and monthly follow-up. Automation, artificial intelligence, custom software and proprietary tools join when they speed up the result — not as a bundle bought before the problem is understood.',
    cta: 'I want to map my company',
    secondary: 'See how it works',
    note: 'The diagnosis defines the priority front. Large projects and extraordinary dedication keep their own scope.',
    message: 'Hello! I want to map my company and see whether Tironi Tech Club is the right fit.',
    member: 'ONGOING PARTNER',
    card: 'Analyze. Implement. Follow up.',
    connection: 'A partner for the operation, not another tool vendor.',
    benefits: [
      ['Diagnosis', 'Clarity on where the operation loses time, money or control.'],
      ['Priorities', 'One critical front at a time, guided by data and business impact.'],
      ['Implementation', 'The change leaves the slide: process, automation, integration or software.'],
      ['Follow-up', 'Indicators reviewed every month, with the next priority already visible.'],
      ['Technology as a means', 'AI, automation and software join when they speed up the result.'],
      ['Less fragmentation', 'Strategy, data and execution working in the same direction.'],
    ],
    outcomes: ['Prioritize', 'Execute', 'Measure', 'Evolve'],
    plansTitle: 'Plans by depth of involvement',
    plansIntro: 'What changes from one plan to the next is depth, the number of fronts and execution priority.',
    plansNote: 'Execution capacity still exists to protect delivery. It is no longer what the commercial conversation compares. Special projects keep a separate scope.',
    plansHeaders: ['Plan', 'Reference', 'What you buy', 'Who it is for'],
    plans: [
      ['Club Essencial', 'R$ 4,900/month', 'Clarity, priorities and execution on one critical business front.', 'A company that already operates and sells, and needs to organize processes, indicators and the first improvements.'],
      ['Club Growth', 'R$ 8,900/month', 'Active follow-up across several fronts, with data, processes, automation and integrated tools.', 'A growing company with an active commercial and administrative operation and recurring bottlenecks.'],
      ['Club Partner', 'from R$ 14,900/month', 'Tironi as an ongoing extension of management and technology, with more depth and execution priority.', 'A more structured SME that needs one recurring partner instead of several vendors.'],
    ],
  },
  es: {
    eyebrow: 'TRANSFORMACIÓN CONTINUA',
    title: ['El Club entra', 'en la operación', 'y hace que el cambio ocurra.'],
    description: 'Diagnóstico, prioridades, implementación y seguimiento mensual. Automatización, inteligencia artificial, software a medida y herramientas propias entran cuando aceleran el resultado — no como un paquete comprado antes de entender el problema.',
    cta: 'Quiero mapear mi empresa',
    secondary: 'Conocer cómo funciona',
    note: 'El diagnóstico define el frente prioritario. Los proyectos grandes y la dedicación extraordinaria siguen con alcance propio.',
    message: '¡Hola! Quiero mapear mi empresa y entender si Tironi Tech Club tiene sentido.',
    member: 'SOCIO CONTINUO',
    card: 'Analizar. Implementar. Acompañar.',
    connection: 'Un socio para la operación, no otro proveedor de herramientas.',
    benefits: [
      ['Diagnóstico', 'Claridad sobre dónde la operación pierde tiempo, dinero o control.'],
      ['Prioridades', 'Un frente crítico a la vez, orientado por datos y por el impacto en el negocio.'],
      ['Implementación', 'El cambio sale del papel: proceso, automatización, integración o software.'],
      ['Seguimiento', 'Indicadores revisados mes a mes, con la próxima prioridad ya visible.'],
      ['Tecnología como medio', 'IA, automatización y software entran cuando aceleran el resultado.'],
      ['Menos fragmentación', 'Estrategia, datos y ejecución trabajando en la misma dirección.'],
    ],
    outcomes: ['Priorizar', 'Ejecutar', 'Medir', 'Evolucionar'],
    plansTitle: 'Planes por nivel de involucramiento',
    plansIntro: 'Lo que cambia de un plan a otro es la profundidad, la cantidad de frentes y la prioridad de ejecución.',
    plansNote: 'La capacidad de ejecución sigue existiendo para proteger la entrega. Deja de ser lo que se compara en la conversación comercial. Los proyectos especiales entran con alcance aparte.',
    plansHeaders: ['Plan', 'Referencia', 'Qué compras', 'Para quién'],
    plans: [
      ['Club Essencial', 'R$ 4.900/mes', 'Claridad, prioridades y ejecución en un frente crítico del negocio.', 'Empresa que ya opera y vende, pero necesita organizar procesos, indicadores y las primeras mejoras.'],
      ['Club Growth', 'R$ 8.900/mes', 'Seguimiento activo de varios frentes, con datos, procesos, automatización y herramientas integradas.', 'Empresa en crecimiento, con operación comercial y administrativa activa y cuellos de botella recurrentes.'],
      ['Club Partner', 'desde R$ 14.900/mes', 'Tironi como extensión continua de la gestión y la tecnología, con más profundidad y prioridad de ejecución.', 'Pyme más estructurada, que necesita un socio recurrente en lugar de varios proveedores.'],
    ],
  },
};
