export const clubContent = {
  pt: {
    eyebrow: 'CONEXÕES QUE MOVEM NEGÓCIOS',
    title: ['Sua empresa.', 'Mais inteligente.', 'A cada mês.'],
    description: 'Tecnologia, IA, automação e estratégia aplicadas ao crescimento do seu negócio. Um clube para quem quer transformar boas ideias em próximos passos.',
    cta: 'Fazer parte do Club',
    note: 'Conheça o Club e as condições para participar.',
    message: 'Olá! Vim pelo site da TironiTech e quero conhecer o Tironi Tech Club e as condições para participar.',
    member: 'MEMBRO EXCLUSIVO',
    card: 'Ideias reais. Negócios maiores.',
    connection: 'Grandes negócios nascem de boas conexões.',
    benefits: [
      ['Diagnóstico da empresa', 'Clareza para identificar oportunidades e definir prioridades.'],
      ['Agentes de IA', 'Inteligência artificial mais próxima da sua operação.'],
      ['Automações prontas', 'Menos tarefas repetitivas. Mais tempo para crescer.'],
      ['Ferramentas exclusivas', 'Recursos selecionados para evoluir o seu negócio.'],
      ['Comunidade de empresários', 'Trocas, conexões e novas perspectivas com quem empreende.'],
      ['Condições especiais', 'Benefícios para dar os próximos passos com a TironiTech.'],
    ],
    outcomes: ['Mais produtividade', 'Mais possibilidades', 'Mais conexões', 'Mais liberdade'],
  },
  en: {
    eyebrow: 'CONNECTIONS THAT MOVE BUSINESS FORWARD',
    title: ['Your business.', 'Smarter.', 'Every month.'],
    description: 'Technology, AI, automation and strategy applied to business growth. A club for turning good ideas into next steps.',
    cta: 'Join the Club', note: 'Explore the Club and membership conditions.',
    message: 'Hello! I found TironiTech online and would like to learn about the Tironi Tech Club and membership conditions.',
    member: 'EXCLUSIVE MEMBER', card: 'Real ideas. Bigger businesses.',
    connection: 'Great businesses start with meaningful connections.',
    benefits: [
      ['Business assessment', 'Clarity to identify opportunities and set priorities.'],
      ['AI agents', 'Artificial intelligence closer to your daily operations.'],
      ['Ready-made automations', 'Fewer repetitive tasks. More time to grow.'],
      ['Exclusive tools', 'Selected resources to move your business forward.'],
      ['Business community', 'Exchange ideas and connect with fellow entrepreneurs.'],
      ['Special conditions', 'Member benefits for your next steps with TironiTech.'],
    ],
    outcomes: ['More productivity', 'More possibilities', 'More connections', 'More freedom'],
  },
  es: {
    eyebrow: 'CONEXIONES QUE IMPULSAN NEGOCIOS',
    title: ['Tu empresa.', 'Más inteligente.', 'Cada mes.'],
    description: 'Tecnología, IA, automatización y estrategia aplicadas al crecimiento de tu negocio. Un club para convertir buenas ideas en próximos pasos.',
    cta: 'Formar parte del Club', note: 'Conoce el Club y las condiciones para participar.',
    message: '¡Hola! Vi el sitio de TironiTech y quiero conocer el Tironi Tech Club y las condiciones para participar.',
    member: 'MIEMBRO EXCLUSIVO', card: 'Ideas reales. Negocios más grandes.',
    connection: 'Los grandes negocios nacen de buenas conexiones.',
    benefits: [
      ['Diagnóstico empresarial', 'Claridad para identificar oportunidades y definir prioridades.'],
      ['Agentes de IA', 'Inteligencia artificial más cerca de tu operación.'],
      ['Automatizaciones listas', 'Menos tareas repetitivas. Más tiempo para crecer.'],
      ['Herramientas exclusivas', 'Recursos seleccionados para impulsar tu negocio.'],
      ['Comunidad empresarial', 'Intercambios, conexiones y perspectivas entre emprendedores.'],
      ['Condiciones especiales', 'Beneficios para dar los próximos pasos con TironiTech.'],
    ],
    outcomes: ['Más productividad', 'Más posibilidades', 'Más conexiones', 'Más libertad'],
  },
};
