export const corporateOverrides = {
  pt: {
    nav: { services: "Serviços", clients: "Clientes", systems: "Sistemas", projects: "Projetos", contact: "Contato", cta: "Agendar diagnóstico", openMenu: "Abrir menu", closeMenu: "Fechar menu", languageLabel: "Idioma" },
    hero: {
      eyebrow: "Tecnologia com clareza, estrutura e evolução",
      title: "Transformamos tecnologia em crescimento real para o seu negócio",
      titleTop: "Transformamos tecnologia",
      titleMiddle: "em crescimento real",
      titleBottom: "para o seu negócio",
      description: "Desenvolvemos software sob medida, automações, IA aplicada e plataformas digitais para empresas que precisam organizar processos, vender mais e evoluir com clareza.",
      primaryCta: "Iniciar projeto",
      secondaryCta: "Conhecer soluções",
      bullets: ["Software sob medida", "Automação de processos", "IA aplicada", "Crescimento digital"],
      metrics: ["Operações mais claras", "Processos mais inteligentes", "Presença digital fortalecida"],
    },
    trustedBy: {
      title: "Empresas e projetos que já passaram pela TironiTech",
      description: "Atuamos na criação de soluções digitais, sites institucionais, plataformas, automações e sistemas pensados para resolver problemas reais de operação e crescimento.",
    },
    about: {
      eyebrow: "Sobre a TironiTech",
      title: "Tecnologia com visão de negócio",
      description: "A TironiTech desenvolve soluções digitais para empresas que precisam transformar processos, estruturar operações e crescer com mais eficiência. Unimos desenvolvimento de software, automação, inteligência artificial aplicada e presença digital para criar produtos que geram valor real.",
      items: [
        { title: "Clareza estratégica", text: "Entendimento do negócio antes de qualquer decisão técnica." },
        { title: "Execução técnica", text: "Construção organizada, moderna e preparada para evoluir." },
        { title: "Produto digital", text: "Soluções pensadas para uso real, operação e crescimento." },
        { title: "Evolução contínua", text: "Melhorias progressivas conforme a operação amadurece." },
      ],
    },
    experience: {
      eyebrow: "Estrutura premium",
      title: "Uma estrutura de tecnologia pensada do diagnóstico à evolução",
      description: "Trabalhamos com clareza de escopo, visão de produto e execução técnica para reduzir risco, acelerar decisões e entregar soluções digitais sustentáveis.",
      pills: ["Diagnóstico", "Estratégia", "Design e experiência", "Desenvolvimento", "Integrações", "Evolução"],
      cards: [
        { tag: "Diagnóstico", title: "Entendimento profundo", text: "Mapeamos processos, gargalos, objetivos e prioridades do negócio." },
        { tag: "Estratégia", title: "Solução com direção", text: "Definimos o melhor caminho digital considerando impacto e viabilidade." },
        { tag: "Produto", title: "Experiência organizada", text: "Desenhamos fluxos, interfaces e jornadas para facilitar o uso." },
        { tag: "Evolução", title: "Crescimento contínuo", text: "Acompanhamos melhorias, integrações e novas necessidades." },
      ],
    },
    solutions: {
      eyebrow: "O que fazemos",
      title: "Soluções digitais para operação, vendas e crescimento",
      items: [
        { title: "Software sob medida", text: "Sistemas personalizados para resolver fluxos específicos da empresa, organizar dados, reduzir tarefas manuais e melhorar a operação." },
        { title: "Sites e plataformas digitais", text: "Sites institucionais, landing pages, dashboards, portais e plataformas digitais com foco em presença, clareza e conversão." },
        { title: "Automação de processos", text: "Automatização de rotinas, integrações, fluxos internos e tarefas repetitivas para aumentar produtividade e reduzir erros." },
        { title: "IA aplicada ao negócio", text: "Inteligência artificial em atendimento, análise, organização de dados, suporte a decisões e otimização de processos." },
        { title: "Integrações e APIs", text: "Conexão entre sistemas, bancos de dados, serviços externos, pagamentos, CRMs e ferramentas usadas pela operação." },
        { title: "Evolução e manutenção", text: "Melhorias contínuas, correções, performance, novas funcionalidades e acompanhamento técnico." },
      ],
    },
    featuredProjects: {
      eyebrow: "Casos e produtos TironiTech",
      title: "Tecnologia aplicada a desafios reais de operação e produto",
      description: "Veja o contexto, a solução construída e as capacidades entregues em projetos da TironiTech.",
      caseLabels: { solution: "Solução construída", impact: "Capacidades entregues" },
      items: [
        { tag: "Cybersecurity / Web3", title: "SignGuard", description: "Solução focada em clareza e proteção para interações com carteiras cripto, ajudando o usuário a entender conexões, assinaturas, aprovações e transações antes da confirmação.", bullets: ["Mais clareza para o usuário", "Mais segurança percebida", "Camada visual premium", "Produto com posicionamento forte"], cta: "Ver projeto" },
        { tag: "Compliance / Privacy Tech", title: "DeleteActPro", description: "Plataforma orientada à automação de compliance para California DROP / SB 362, com fluxo de ingestão, evidências, deleções em cascata e registros preparados para auditoria.", bullets: ["Automação regulatória", "Estrutura auditável", "Operação escalável", "Posicionamento enterprise"], cta: "Conhecer solução" },
        { tag: "Sorteios / Plataforma Digital", title: "Sorteios NewStore", description: "Plataforma digital para gestão de sorteios, reservas, compradores, pagamentos e operação administrativa, com foco em clareza, controle e experiência do usuário.", bullets: ["Gestão de sorteios", "Reservas e compradores", "Painel administrativo", "Operação escalável"], cta: "Conhecer solução" },
      ],
    },
    impact: {
      eyebrow: "Impacto para o negócio",
      title: "Tecnologia que melhora operação, vendas e presença digital",
      description: "A TironiTech estrutura tecnologia para transformar processos em vantagem operacional e presença digital em crescimento real.",
      items: [
        { title: "Operação mais eficiente", text: "Sistemas e automações reduzem retrabalho, organizam dados e tornam processos mais claros." },
        { title: "Vendas impulsionadas", text: "Páginas, plataformas e fluxos digitais pensados para melhorar conversão e relacionamento com clientes." },
        { title: "Processos integrados", text: "Conectamos ferramentas, APIs e bancos de dados para diminuir tarefas manuais e centralizar informações." },
        { title: "Presença digital fortalecida", text: "Criamos experiências digitais profissionais que aumentam autoridade, confiança e percepção de valor." },
        { title: "Decisões com mais clareza", text: "Dashboards, relatórios e dados organizados para apoiar crescimento e gestão." },
        { title: "Evolução contínua", text: "A tecnologia acompanha a operação conforme o negócio cresce." },
      ],
    },
    process: {
      eyebrow: "Processo de trabalho",
      title: "Da estratégia ao produto digital em ciclos claros",
      steps: [
        { title: "Diagnóstico", text: "Entendemos o negócio, os processos, os gargalos e os objetivos." },
        { title: "Estratégia", text: "Definimos a melhor solução digital, priorizando impacto real e viabilidade." },
        { title: "Design e experiência", text: "Organizamos interface, fluxos e experiência para facilitar o uso." },
        { title: "Desenvolvimento", text: "Construímos com tecnologia moderna, código limpo e foco em estabilidade." },
        { title: "Integrações", text: "Conectamos sistemas, bancos, APIs, automações e ferramentas necessárias." },
        { title: "Evolução", text: "Acompanhamos melhorias, ajustes e crescimento da solução." },
      ],
    },
    whyChoose: {
      eyebrow: "Por que escolher a TironiTech",
      title: "Uma parceira estratégica para estruturar tecnologia com resultado",
      items: [
        { title: "Visão consultiva", text: "A tecnologia nasce conectada ao objetivo do negócio, não apenas à entrega técnica." },
        { title: "Execução enxuta", text: "Priorizamos clareza, organização e decisões que reduzem desperdício." },
        { title: "Base técnica sólida", text: "Projetos pensados para estabilidade, manutenção e evolução." },
        { title: "Presença digital forte", text: "Soluções que comunicam confiança e aumentam percepção de valor." },
      ],
    },
    finalCta: { title: "Vamos transformar sua operação em uma solução digital mais clara e eficiente", description: "Se você precisa de software sob medida, automação, IA aplicada ou uma presença digital mais forte, a TironiTech pode estruturar isso com visão de negócio e execução técnica." },
    footer: { text: "Tecnologia com clareza, estrutura e evolução para negócios que querem crescer.", navTitle: "Navegação", contactTitle: "Contato", whatsapp: "WhatsApp", cookiePreferences: "Preferências de cookies", privacy: "Política de Privacidade" },
    cookies: {
      label: "Preferências de cookies",
      banner: "Usamos cookies para medir e melhorar sua experiência. Você controla os cookies não essenciais.",
      text: "A TironiTech utiliza cookies para melhorar sua experiência, lembrar preferências e entender como o site é utilizado. Você pode aceitar todos, recusar cookies não essenciais ou personalizar suas escolhas.",
      privacy: "Política de Privacidade",
      acceptAll: "Aceitar todos",
      accept: "Aceitar todos",
      reject: "Recusar",
      preferences: "Preferências",
      savePreferences: "Salvar preferências",
      rejectNonEssential: "Recusar não essenciais",
      modalTitle: "Preferências de cookies",
      modalText: "Gerencie como a TironiTech pode usar cookies no seu navegador. Cookies necessários permanecem sempre ativos para manter o site funcionando corretamente.",
      close: "Fechar preferências de cookies",
      alwaysActive: "Sempre ativo",
      enabled: "Ativo",
      disabled: "Inativo",
      categories: {
        necessary: { title: "Necessários", description: "Essenciais para o funcionamento básico do site e não podem ser desativados." },
        preferences: { title: "Preferências", description: "Ajudam a lembrar escolhas como idioma e configurações de navegação." },
        analytics: { title: "Analytics", description: "Ajudam a entender como visitantes usam o site para melhorar desempenho, conteúdo e experiência." },
        marketing: { title: "Marketing", description: "Podem ser usados para medir campanhas, melhorar divulgação e personalizar comunicações." },
      },
    },
  },  en: {
    nav: { services: "Services", clients: "Clients", systems: "Systems", projects: "Projects", contact: "Contact", cta: "Schedule a diagnosis", openMenu: "Open menu", closeMenu: "Close menu", languageLabel: "Language" },
    hero: { eyebrow: "Technology with clarity, structure and evolution", title: "We turn technology into real growth for your business", titleTop: "We turn technology", titleMiddle: "into real growth", titleBottom: "for your business", description: "We build custom software, automations, applied AI and digital platforms for companies that need to organize processes, sell more and evolve with clarity.", primaryCta: "Start project", secondaryCta: "Explore solutions", bullets: ["Custom software", "Process automation", "Applied AI", "Digital growth"], metrics: ["Clearer operations", "Smarter processes", "Stronger digital presence"] },
    trustedBy: { title: "Companies and projects that have worked with TironiTech", description: "We create digital solutions, institutional websites, platforms, automations and systems designed to solve real operation and growth challenges." },
    about: { eyebrow: "About TironiTech", title: "Technology with business vision", description: "TironiTech builds digital solutions for companies that need to transform processes, structure operations and grow with more efficiency. We combine software development, automation, applied AI and digital presence to create products that generate real value.", items: [ { title: "Strategic clarity", text: "Understanding the business before any technical decision." }, { title: "Technical execution", text: "Organized, modern builds prepared to evolve." }, { title: "Digital product", text: "Solutions designed for real use, operation and growth." }, { title: "Continuous evolution", text: "Progressive improvements as the operation matures." } ] },
    experience: { eyebrow: "Premium structure", title: "A technology structure designed from diagnosis to evolution", description: "We work with scope clarity, product vision and technical execution to reduce risk, accelerate decisions and deliver sustainable digital solutions.", pills: ["Diagnosis", "Strategy", "Design and experience", "Development", "Integrations", "Evolution"], cards: [ { tag: "Diagnosis", title: "Deep understanding", text: "We map processes, bottlenecks, goals and business priorities." }, { tag: "Strategy", title: "Solution with direction", text: "We define the best digital path considering impact and feasibility." }, { tag: "Product", title: "Organized experience", text: "We design flows, interfaces and journeys that make use easier." }, { tag: "Evolution", title: "Continuous growth", text: "We support improvements, integrations and new needs." } ] },
    solutions: { eyebrow: "What we do", title: "Digital solutions for operations, sales and growth", items: [ { title: "Custom software", text: "Personalized systems to solve specific company flows, organize data, reduce manual work and improve operations." }, { title: "Websites and digital platforms", text: "Institutional websites, landing pages, dashboards, portals and platforms focused on presence, clarity and conversion." }, { title: "Process automation", text: "Automation of routines, integrations, internal flows and repetitive tasks to increase productivity and reduce errors." }, { title: "AI applied to business", text: "Artificial intelligence for service, analysis, data organization, decision support and process optimization." }, { title: "Integrations and APIs", text: "Connection between systems, databases, external services, payments, CRMs and operational tools." }, { title: "Evolution and maintenance", text: "Continuous improvements, fixes, performance, new features and technical support." } ] },
    featuredProjects: { eyebrow: "TironiTech cases and products", title: "Technology applied to real operations and product challenges", description: "See the context, the solution built and the capabilities delivered in TironiTech projects.", caseLabels: { solution: "Solution built", impact: "Capabilities delivered" }, items: [ { tag: "Cybersecurity / Web3", title: "SignGuard", description: "A solution focused on clarity and protection for crypto wallet interactions, helping users understand connections, signatures, approvals and transactions before confirmation.", bullets: ["More clarity for users", "Greater perceived security", "Premium visual layer", "Strong product positioning"], cta: "View project" }, { tag: "Compliance / Privacy Tech", title: "DeleteActPro", description: "Platform oriented to compliance automation for California DROP / SB 362, with ingestion flow, evidence, cascade deletions and audit-ready records.", bullets: ["Regulatory automation", "Auditable structure", "Scalable operation", "Enterprise positioning"], cta: "Explore solution" }, { tag: "Raffles / Digital Platform", title: "Sorteios NewStore", description: "Digital platform for managing raffles, reservations, buyers, payments and administrative operations, focused on clarity, control and user experience.", bullets: ["Raffle management", "Reservations and buyers", "Admin dashboard", "Scalable operation"], cta: "Explore solution" } ] },
    impact: { eyebrow: "Business impact", title: "Technology that improves operations, sales and digital presence", description: "TironiTech structures technology to turn processes into operational advantage and digital presence into real growth.", items: [ { title: "More efficient operations", text: "Systems and automations reduce rework, organize data and make processes clearer." }, { title: "Sales enabled", text: "Pages, platforms and digital flows designed to improve conversion and customer relationships." }, { title: "Integrated processes", text: "We connect tools, APIs and databases to reduce manual tasks and centralize information." }, { title: "Stronger digital presence", text: "Professional digital experiences that increase authority, trust and perceived value." }, { title: "Clearer decisions", text: "Dashboards, reports and organized data to support growth and management." }, { title: "Continuous evolution", text: "Technology follows the operation as the business grows." } ] },
    process: { eyebrow: "Work process", title: "From strategy to digital product in clear cycles", steps: [ { title: "Diagnosis", text: "We understand business, processes, bottlenecks and goals." }, { title: "Strategy", text: "We define the best digital solution, prioritizing real impact and feasibility." }, { title: "Design and experience", text: "We organize interface, flows and experience to make use easier." }, { title: "Development", text: "We build with modern technology, clean code and stability focus." }, { title: "Integrations", text: "We connect systems, databases, APIs, automations and required tools." }, { title: "Evolution", text: "We support improvements, adjustments and solution growth." } ] },
    whyChoose: { eyebrow: "Why choose TironiTech", title: "A strategic partner to structure technology with results", items: [ { title: "Consultative vision", text: "Technology is connected to business goals, not only to technical delivery." }, { title: "Lean execution", text: "We prioritize clarity, organization and decisions that reduce waste." }, { title: "Solid technical base", text: "Projects designed for stability, maintenance and evolution." }, { title: "Strong digital presence", text: "Solutions that communicate trust and increase perceived value." } ] },
    finalCta: { title: "Let's transform your operation into a clearer and more efficient digital solution", description: "If you need custom software, automation, applied AI or a stronger digital presence, TironiTech can structure it with business vision and technical execution." },
    footer: { text: "Technology with clarity, structure and evolution for businesses that want to grow.", navTitle: "Navigation", contactTitle: "Contact", whatsapp: "WhatsApp", cookiePreferences: "Cookie preferences", privacy: "Privacy Policy" },
    cookies: {
      label: "Cookie preferences",
      banner: "We use cookies to measure and improve your experience. You control non-essential cookies.",
      text: "TironiTech uses cookies to improve your experience, remember preferences and understand how the website is used. You can accept all, reject non-essential cookies or customize your choices.",
      privacy: "Privacy Policy",
      acceptAll: "Accept all",
      accept: "Accept all",
      reject: "Reject",
      preferences: "Preferences",
      savePreferences: "Save preferences",
      rejectNonEssential: "Reject non-essential",
      modalTitle: "Cookie preferences",
      modalText: "Manage how TironiTech can use cookies in your browser. Necessary cookies always remain active to keep the website working properly.",
      close: "Close cookie preferences",
      alwaysActive: "Always active",
      enabled: "Enabled",
      disabled: "Disabled",
      categories: {
        necessary: { title: "Necessary", description: "Essential for the basic operation of the website and cannot be disabled." },
        preferences: { title: "Preferences", description: "Help remember choices such as language and navigation settings." },
        analytics: { title: "Analytics", description: "Help understand how visitors use the website to improve performance, content and experience." },
        marketing: { title: "Marketing", description: "May be used to measure campaigns, improve promotion and personalize communications." },
      },
    },
  },  es: {
    nav: { services: "Servicios", clients: "Clientes", systems: "Sistemas", projects: "Proyectos", contact: "Contacto", cta: "Agendar diagnóstico", openMenu: "Abrir menú", closeMenu: "Cerrar menú", languageLabel: "Idioma" },
    hero: { eyebrow: "Tecnología con claridad, estructura y evolución", title: "Transformamos tecnología en crecimiento real para tu negocio", titleTop: "Transformamos tecnología", titleMiddle: "en crecimiento real", titleBottom: "para tu negocio", description: "Desarrollamos software a medida, automatizaciones, IA aplicada y plataformas digitales para empresas que necesitan organizar procesos, vender más y evolucionar con claridad.", primaryCta: "Iniciar proyecto", secondaryCta: "Conocer soluciones", bullets: ["Software a medida", "Automatización de procesos", "IA aplicada", "Crecimiento digital"], metrics: ["Operaciones más claras", "Procesos más inteligentes", "Presencia digital fortalecida"] },
    trustedBy: { title: "Empresas y proyectos que ya pasaron por TironiTech", description: "Creamos soluciones digitales, sitios institucionales, plataformas, automatizaciones y sistemas pensados para resolver problemas reales de operación y crecimiento." },
    about: { eyebrow: "Sobre TironiTech", title: "Tecnología con visión de negocio", description: "TironiTech desarrolla soluciones digitales para empresas que necesitan transformar procesos, estructurar operaciones y crecer con más eficiencia. Unimos desarrollo de software, automatización, inteligencia artificial aplicada y presencia digital para crear productos que generan valor real.", items: [ { title: "Claridad estratégica", text: "Entendimiento del negocio antes de cualquier decisión técnica." }, { title: "Ejecución técnica", text: "Construcción organizada, moderna y preparada para evolucionar." }, { title: "Producto digital", text: "Soluciones pensadas para uso real, operación y crecimiento." }, { title: "Evolución continua", text: "Mejoras progresivas conforme la operación madura." } ] },
    experience: { eyebrow: "Estructura premium", title: "Una estructura de tecnología pensada del diagnóstico a la evolución", description: "Trabajamos con claridad de alcance, visión de producto y ejecución técnica para reducir riesgos, acelerar decisiones y entregar soluciones digitales sostenibles.", pills: ["Diagnóstico", "Estrategia", "Diseño y experiencia", "Desarrollo", "Integraciones", "Evolución"], cards: [ { tag: "Diagnóstico", title: "Entendimiento profundo", text: "Mapeamos procesos, cuellos de botella, objetivos y prioridades del negocio." }, { tag: "Estrategia", title: "Solución con dirección", text: "Definimos el mejor camino digital considerando impacto y viabilidad." }, { tag: "Producto", title: "Experiencia organizada", text: "Diseñamos flujos, interfaces y recorridos para facilitar el uso." }, { tag: "Evolución", title: "Crecimiento continuo", text: "Acompañamos mejoras, integraciones y nuevas necesidades." } ] },
    solutions: { eyebrow: "Qué hacemos", title: "Soluciones digitales para operación, ventas y crecimiento", items: [ { title: "Software a medida", text: "Sistemas personalizados para resolver flujos específicos de la empresa, organizar datos, reducir tareas manuales y mejorar la operación." }, { title: "Sitios y plataformas digitales", text: "Sitios institucionales, landing pages, dashboards, portales y plataformas con foco en presencia, claridad y conversión." }, { title: "Automatización de procesos", text: "Automatización de rutinas, integraciones, flujos internos y tareas repetitivas para aumentar productividad y reducir errores." }, { title: "IA aplicada al negocio", text: "Inteligencia artificial en atención, análisis, organización de datos, soporte a decisiones y optimización de procesos." }, { title: "Integraciones y APIs", text: "Conexión entre sistemas, bases de datos, servicios externos, pagos, CRMs y herramientas de operación." }, { title: "Evolución y mantenimiento", text: "Mejoras continuas, correcciones, performance, nuevas funcionalidades y acompañamiento técnico." } ] },
    featuredProjects: { eyebrow: "Casos y productos TironiTech", title: "Tecnología aplicada a desafíos reales de operación y producto", description: "Conoce el contexto, la solución construida y las capacidades entregadas en proyectos de TironiTech.", caseLabels: { solution: "Solución construida", impact: "Capacidades entregadas" }, items: [ { tag: "Cybersecurity / Web3", title: "SignGuard", description: "Solución enfocada en claridad y protección para interacciones con billeteras cripto, ayudando al usuario a entender conexiones, firmas, aprobaciones y transacciones antes de confirmar.", bullets: ["Más claridad para el usuario", "Más seguridad percibida", "Capa visual premium", "Producto con posicionamiento fuerte"], cta: "Ver proyecto" }, { tag: "Compliance / Privacy Tech", title: "DeleteActPro", description: "Plataforma orientada a la automatización de compliance para California DROP / SB 362, con flujo de ingestión, evidencias, eliminaciones en cascada y registros preparados para auditoría.", bullets: ["Automatización regulatoria", "Estructura auditable", "Operación escalable", "Posicionamiento enterprise"], cta: "Conocer solución" }, { tag: "Sorteos / Plataforma Digital", title: "Sorteios NewStore", description: "Plataforma digital para gestionar sorteos, reservas, compradores, pagos y operación administrativa, con foco en claridad, control y experiencia del usuario.", bullets: ["Gestión de sorteos", "Reservas y compradores", "Panel administrativo", "Operación escalable"], cta: "Conocer solución" } ] },
    impact: { eyebrow: "Impacto para el negocio", title: "Tecnología que mejora operación, ventas y presencia digital", description: "TironiTech estructura tecnología para transformar procesos en ventaja operacional y presencia digital en crecimiento real.", items: [ { title: "Operación más eficiente", text: "Sistemas y automatizaciones reducen retrabajo, organizan datos y vuelven los procesos más claros." }, { title: "Ventas impulsadas", text: "Páginas, plataformas y flujos digitales pensados para mejorar conversión y relación con clientes." }, { title: "Procesos integrados", text: "Conectamos herramientas, APIs y bases de datos para disminuir tareas manuales y centralizar información." }, { title: "Presencia digital fortalecida", text: "Experiencias digitales profesionales que aumentan autoridad, confianza y percepción de valor." }, { title: "Decisiones con más claridad", text: "Dashboards, informes y datos organizados para apoyar crecimiento y gestión." }, { title: "Evolución continua", text: "La tecnología acompaña la operación a medida que el negocio crece." } ] },
    process: { eyebrow: "Proceso de trabajo", title: "De la estrategia al producto digital en ciclos claros", steps: [ { title: "Diagnóstico", text: "Entendemos el negocio, los procesos, los cuellos de botella y los objetivos." }, { title: "Estrategia", text: "Definimos la mejor solución digital, priorizando impacto real y viabilidad." }, { title: "Diseño y experiencia", text: "Organizamos interfaz, flujos y experiencia para facilitar el uso." }, { title: "Desarrollo", text: "Construimos con tecnología moderna, código limpio y foco en estabilidad." }, { title: "Integraciones", text: "Conectamos sistemas, bases, APIs, automatizaciones y herramientas necesarias." }, { title: "Evolución", text: "Acompañamos mejoras, ajustes y crecimiento de la solución." } ] },
    whyChoose: { eyebrow: "Por qué elegir TironiTech", title: "Una socia estratégica para estructurar tecnología con resultado", items: [ { title: "Visión consultiva", text: "La tecnología nace conectada al objetivo del negocio, no solo a la entrega técnica." }, { title: "Ejecución ágil", text: "Priorizamos claridad, organización y decisiones que reducen desperdicio." }, { title: "Base técnica sólida", text: "Proyectos pensados para estabilidad, mantenimiento y evolución." }, { title: "Presencia digital fuerte", text: "Soluciones que comunican confianza y aumentan percepción de valor." } ] },
    finalCta: { title: "Transformemos tu operación en una solución digital más clara y eficiente", description: "Si necesitas software a medida, automatización, IA aplicada o una presencia digital más fuerte, TironiTech puede estructurarlo con visión de negocio y ejecución técnica." },
    footer: { text: "Tecnología con claridad, estructura y evolución para negocios que quieren crecer.", navTitle: "Navegación", contactTitle: "Contacto", whatsapp: "WhatsApp", cookiePreferences: "Preferencias de cookies", privacy: "Política de Privacidad" },
    cookies: {
      label: "Preferencias de cookies",
      banner: "Usamos cookies para medir y mejorar tu experiencia. Tú controlas las cookies no esenciales.",
      text: "TironiTech utiliza cookies para mejorar tu experiencia, recordar preferencias y entender cómo se utiliza el sitio. Puedes aceptar todos, rechazar cookies no esenciales o personalizar tus opciones.",
      privacy: "Política de Privacidad",
      acceptAll: "Aceptar todos",
      accept: "Aceptar todos",
      reject: "Rechazar",
      preferences: "Preferencias",
      savePreferences: "Guardar preferencias",
      rejectNonEssential: "Rechazar no esenciales",
      modalTitle: "Preferencias de cookies",
      modalText: "Gestiona cómo TironiTech puede usar cookies en tu navegador. Las cookies necesarias permanecen siempre activas para mantener el sitio funcionando correctamente.",
      close: "Cerrar preferencias de cookies",
      alwaysActive: "Siempre activo",
      enabled: "Activo",
      disabled: "Inactivo",
      categories: {
        necessary: { title: "Necesarias", description: "Esenciales para el funcionamiento básico del sitio y no se pueden desactivar." },
        preferences: { title: "Preferencias", description: "Ayudan a recordar opciones como idioma y configuraciones de navegación." },
        analytics: { title: "Analytics", description: "Ayudan a entender cómo los visitantes usan el sitio para mejorar rendimiento, contenido y experiencia." },
        marketing: { title: "Marketing", description: "Pueden usarse para medir campañas, mejorar la divulgación y personalizar comunicaciones." },
      },
    },
  },
};
