export const corporateOverrides = {
  pt: {
    nav: { services: "Serviços", clients: "Clientes", systems: "Sistemas", projects: "Projetos", contact: "Contato", club: "Club", method: "Como funciona", tools: "Ferramentas", development: "Desenvolvimento", results: "Resultados", insights: "Insights", cta: "Agendar diagnóstico", openMenu: "Abrir menu", closeMenu: "Fechar menu", languageLabel: "Idioma" },
    hero: {
      eyebrow: "Tecnologia com clareza, estrutura e evolução",
      title: "Transformamos tecnologia em crescimento real para o seu negócio",
      titleTop: "Transformamos tecnologia",
      titleMiddle: "em crescimento real",
      titleBottom: "para o seu negócio",
      description: "Desenvolvemos software sob medida, automações, IA aplicada e plataformas digitais para empresas que precisam organizar processos, vender mais e evoluir com clareza.",
      primaryCta: "Iniciar projeto",
      secondaryCta: "Conhecer soluções",
      bullets: ["Software sob medida", "Automação de processos", "IA aplicada", "Crescimento digital"],
      metrics: ["Operações mais claras", "Processos mais inteligentes", "Presença digital fortalecida"],
    },
    trustedBy: {
      title: "Empresas e projetos que já passaram pela TironiTech",
      description: "Atuamos na criação de soluções digitais, sites institucionais, plataformas, automações e sistemas pensados para resolver problemas reais de operação e crescimento.",
    },
    about: {
      eyebrow: "A Tironi Tech",
      title: "Transformação empresarial com execução",
      description: "A Tironi Tech entra na operação, analisa processos e dados, implementa melhorias com inteligência artificial, automação de processos empresariais e software sob medida, e acompanha os resultados. O Tironi Tech Club é a forma contínua de fazer isso. Desenvolvimento sob medida segue disponível quando o escopo pede um projeto específico.",
      items: [
        { title: "Clareza estratégica", text: "Entendimento do negócio antes de qualquer decisão técnica." },
        { title: "Execução técnica", text: "Construção organizada, moderna e preparada para evoluir." },
        { title: "Produto digital", text: "Soluções pensadas para uso real, operação e crescimento." },
        { title: "Evolução contínua", text: "Melhorias progressivas conforme a operação amadurece." },
      ],
    },
    experience: {
      eyebrow: "Estrutura premium",
      title: "Uma estrutura de tecnologia pensada do diagnóstico à evolução",
      description: "Trabalhamos com clareza de escopo, visão de produto e execução técnica para reduzir risco, acelerar decisões e entregar soluções digitais sustentáveis.",
      pills: ["Diagnóstico", "Estratégia", "Design e experiência", "Desenvolvimento", "Integrações", "Evolução"],
      cards: [
        { tag: "Diagnóstico", title: "Entendimento profundo", text: "Mapeamos processos, gargalos, objetivos e prioridades do negócio." },
        { tag: "Estratégia", title: "Solução com direção", text: "Definimos o melhor caminho digital considerando impacto e viabilidade." },
        { tag: "Produto", title: "Experiência organizada", text: "Desenhamos fluxos, interfaces e jornadas para facilitar o uso." },
        { tag: "Evolução", title: "Crescimento contínuo", text: "Acompanhamos melhorias, integrações e novas necessidades." },
      ],
    },
    solutions: {
      eyebrow: "Capacidades de execução",
      title: "Tecnologia entra quando acelera o resultado",
      items: [
        { title: "Software sob medida", text: "Sistemas personalizados para resolver fluxos específicos da empresa, organizar dados, reduzir tarefas manuais e melhorar a operação." },
        { title: "Sites e plataformas digitais", text: "Sites institucionais, landing pages, dashboards, portais e plataformas digitais com foco em presença, clareza e conversão." },
        { title: "Automação de processos", text: "Automatização de rotinas, integrações, fluxos internos e tarefas repetitivas para aumentar produtividade e reduzir erros." },
        { title: "IA aplicada ao negócio", text: "Inteligência artificial em atendimento, análise, organização de dados, suporte a decisões e otimização de processos." },
        { title: "Integrações e APIs", text: "Conexão entre sistemas, bancos de dados, serviços externos, pagamentos, CRMs e ferramentas usadas pela operação." },
        { title: "Evolução e manutenção", text: "Melhorias contínuas, correções, performance, novas funcionalidades e acompanhamento técnico." },
      ],
    },
    chatbo: {
      eyebrow: "CHATBÔ • IA COMERCIAL",
      title: "Transforme conversas em oportunidades de venda com IA",
      description: "Centralize seus canais, qualifique leads a qualquer hora e acompanhe cada oportunidade em um ambiente criado para dar velocidade ao time comercial.",
      features: [
        { title: "Atendimento multicanal", text: "WhatsApp, Instagram, Facebook, Telegram, WebChat e e-mail em uma única operação." },
        { title: "Qualificação com IA", text: "O agente faz a triagem, organiza o contexto e prepara oportunidades para o time." },
        { title: "Funil e recuperação", text: "Acompanhe negociações, follow-ups e leads parados sem depender de controles dispersos." },
        { title: "IA junto com pessoas", text: "Sugestões de resposta aceleram o atendimento enquanto sua equipe mantém o controle." },
      ],
      primaryCta: "Testar grátis por 5 dias",
      secondaryCta: "Ver como funciona",
      trustLabel: "Condições do teste",
      trust: ["Sem cartão", "Treinamento incluso", "Suporte humano"],
      status: "IA + TIME ONLINE",
      channelsLabel: "Canais integrados",
      channels: ["WhatsApp", "Instagram", "WebChat", "E-mail"],
      imageAlt: "Painel comercial do ChatBô com conversas, oportunidades e assistência de IA",
    },
    featuredProjects: {
      eyebrow: "Resultados",
      title: "Execução que já virou operação",
      description: "Veja o contexto, a solução construída e as capacidades entregues em projetos da TironiTech.",
      caseLabels: { solution: "Solução construída", impact: "Capacidades entregues" },
      items: [
        { tag: "Cybersecurity / Web3", title: "SignGuard", description: "Solução focada em clareza e proteção para interações com carteiras cripto, ajudando o usuário a entender conexões, assinaturas, aprovações e transações antes da confirmação.", bullets: ["Mais clareza para o usuário", "Mais segurança percebida", "Camada visual premium", "Produto com posicionamento forte"], cta: "Ver projeto" },
        { tag: "Compliance / Privacy Tech", title: "DeleteActPro", description: "Plataforma orientada à automação de compliance para California DROP / SB 362, com fluxo de ingestão, evidências, deleções em cascata e registros preparados para auditoria.", bullets: ["Automação regulatória", "Estrutura auditável", "Operação escalável", "Posicionamento enterprise"], cta: "Conhecer solução" },
        { tag: "Sorteios / Plataforma Digital", title: "Sorteios NewStore", description: "Plataforma digital para gestão de sorteios, reservas, compradores, pagamentos e operação administrativa, com foco em clareza, controle e experiência do usuário.", bullets: ["Gestão de sorteios", "Reservas e compradores", "Painel administrativo", "Operação escalável"], cta: "Conhecer solução" },
        { tag: "EdTech / Simulador Comercial", title: "Sales Game", description: "Jogo de estratégia comercial desenvolvido para Casagrande Consultoria e Multiplier, com partidas locais e online, decisões de caixa, clientes, equipe, canais, ERP, treinamento e eventos de mercado.", bullets: ["Site e Play Store", "Multiplayer e jogo local", "Gestão comercial", "Experiência responsiva"], cta: "Jogar Sales Game" },
        { tag: "Sorteios / E-commerce", title: "Sorteios xNaMai", description: "Plataforma de sorteios integrada à experiência xNaMai, com seleção de números, conta do participante, regras de crédito e acompanhamento da campanha.", bullets: ["Escolha de números", "Conta do participante", "Créditos integrados", "Operação responsiva"], cta: "Ver plataforma" },
        { tag: "Subscription Tech / Clube de vantagens", title: "XNaMai Club", description: "Plataforma de assinaturas empresariais desenvolvida para transformar vantagens comerciais em uma nova linha de receita recorrente, com planos, simulador de economia, catálogo e gestão segura da assinatura.", bullets: ["R$ 200 mil em receita recorrente", "Planos e cobrança recorrente", "Simulador de economia", "Jornada de assinatura segura"], cta: "Conhecer o projeto" },
        { tag: "Sales Tech / Outreach", title: "MestreLead", description: "Produto de prospecção por e-mail com campanhas, modelos, contatos, CRM, fila de envio, relatórios e ingestão de bases para centralizar a operação comercial.", bullets: ["Campanhas de e-mail", "CRM integrado", "Fila e relatórios", "Ingestão de leads"], cta: "Conhecer produto" },
        { tag: "Data / Business Intelligence", title: "BI Personalizado", description: "Painéis de BI desenvolvidos sob medida para clientes estratégicos, reunindo pedidos, produtos, compradores, retenção, LTV, vendedores, estoque, logística e qualidade dos dados.", bullets: ["Indicadores sob medida", "Dados comerciais", "Retenção e LTV", "Sincronização monitorada"], cta: "Criar meu BI" },
        { tag: "AdTech / Shopify App", title: "ProfitPilot Ads", description: "Copiloto de anúncios para Shopify que conecta Meta, Google e TikTok, aplica checklist antes da publicação, protege orçamento com guardrails e mostra performance orientada a lucro.", bullets: ["Shopify App", "Meta, Google e TikTok", "Proteção de orçamento", "Painel profit-first"], cta: "Ver produto" },
      ],
    },
    impact: {
      eyebrow: "Impacto para o negócio",
      title: "Tecnologia que melhora operação, vendas e presença digital",
      description: "A TironiTech estrutura tecnologia para transformar processos em vantagem operacional e presença digital em crescimento real.",
      items: [
        { title: "Operação mais eficiente", text: "Sistemas e automações reduzem retrabalho, organizam dados e tornam processos mais claros." },
        { title: "Vendas impulsionadas", text: "Páginas, plataformas e fluxos digitais pensados para melhorar conversão e relacionamento com clientes." },
        { title: "Processos integrados", text: "Conectamos ferramentas, APIs e bancos de dados para diminuir tarefas manuais e centralizar informações." },
        { title: "Presença digital fortalecida", text: "Criamos experiências digitais profissionais que aumentam autoridade, confiança e percepção de valor." },
        { title: "Decisões com mais clareza", text: "Dashboards, relatórios e dados organizados para apoiar crescimento e gestão." },
        { title: "Evolução contínua", text: "A tecnologia acompanha a operação conforme o negócio cresce." },
      ],
    },
    process: {
      eyebrow: "Como funciona",
      title: "Analisar, priorizar, implementar, medir e evoluir",
      steps: [
        { title: "Analisar", text: "Entramos na operação e nos dados para ver onde se perde tempo, dinheiro ou controle." },
        { title: "Priorizar", text: "Escolhemos a frente que mais trava o crescimento." },
        { title: "Implementar", text: "Fazemos a mudança com processo, automação, integração ou software." },
        { title: "Medir", text: "Acompanhamos o indicador combinado, não só a tarefa entregue." },
        { title: "Evoluir", text: "O mês seguinte parte do que funcionou e do que ainda trava." },
      ],
    },
    whyChoose: {
      eyebrow: "Por que escolher a TironiTech",
      title: "Uma parceira estratégica para estruturar tecnologia com resultado",
      items: [
        { title: "Visão consultiva", text: "A tecnologia nasce conectada ao objetivo do negócio, não apenas à entrega técnica." },
        { title: "Execução enxuta", text: "Priorizamos clareza, organização e decisões que reduzem desperdício." },
        { title: "Base técnica sólida", text: "Projetos pensados para estabilidade, manutenção e evolução." },
        { title: "Presença digital forte", text: "Soluções que comunicam confiança e aumentam percepção de valor." },
      ],
    },
    finalCta: { title: "Agende um diagnóstico estratégico", description: "Em uma conversa, mapeamos o que trava o crescimento e o que vale implementar primeiro. O Club é o caminho contínuo; um projeto de desenvolvimento existe quando o escopo pede uma entrega própria." },
    footer: { text: "Entramos no negócio, implementamos a mudança e acompanhamos o resultado.", navTitle: "Navegação", contactTitle: "Contato", whatsapp: "WhatsApp", cookiePreferences: "Preferências de cookies", privacy: "Política de Privacidade" },
    cookies: {
      label: "Preferências de cookies",
      banner: "Usamos cookies para medir e melhorar sua experiência. Você controla os cookies não essenciais.",
      text: "A TironiTech utiliza cookies para melhorar sua experiência, lembrar preferências e entender como o site é utilizado. Você pode aceitar todos, recusar cookies não essenciais ou personalizar suas escolhas.",
      privacy: "Política de Privacidade",
      acceptAll: "Aceitar todos",
      accept: "Aceitar todos",
      reject: "Recusar",
      preferences: "Preferências",
      savePreferences: "Salvar preferências",
      rejectNonEssential: "Recusar não essenciais",
      modalTitle: "Preferências de cookies",
      modalText: "Gerencie como a TironiTech pode usar cookies no seu navegador. Cookies necessários permanecem sempre ativos para manter o site funcionando corretamente.",
      close: "Fechar preferências de cookies",
      alwaysActive: "Sempre ativo",
      enabled: "Ativo",
      disabled: "Inativo",
      categories: {
        necessary: { title: "Necessários", description: "Essenciais para o funcionamento básico do site e não podem ser desativados." },
        preferences: { title: "Preferências", description: "Ajudam a lembrar escolhas como idioma e configurações de navegação." },
        analytics: { title: "Analytics", description: "Medem uso e desempenho e, quando habilitado, permitem mapas de interação e gravações de sessão com campos sensíveis mascarados." },
        marketing: { title: "Marketing", description: "Podem ser usados para medir campanhas, melhorar divulgação e personalizar comunicações." },
      },
    },
  },  en: {
    nav: { services: "Services", clients: "Clients", systems: "Systems", projects: "Projects", contact: "Contact", club: "Club", method: "How it works", tools: "Tools", development: "Development", results: "Results", insights: "Insights", cta: "Schedule diagnosis", openMenu: "Open menu", closeMenu: "Close menu", languageLabel: "Language" },
    hero: { eyebrow: "Technology with clarity, structure and evolution", title: "We turn technology into real growth for your business", titleTop: "We turn technology", titleMiddle: "into real growth", titleBottom: "for your business", description: "We build custom software, automations, applied AI and digital platforms for companies that need to organize processes, sell more and evolve with clarity.", primaryCta: "Start project", secondaryCta: "Explore solutions", bullets: ["Custom software", "Process automation", "Applied AI", "Digital growth"], metrics: ["Clearer operations", "Smarter processes", "Stronger digital presence"] },
    trustedBy: { title: "Companies and projects that have worked with TironiTech", description: "We create digital solutions, institutional websites, platforms, automations and systems designed to solve real operation and growth challenges." },
    about: { eyebrow: "Tironi Tech", title: "Business transformation with execution", description: "Tironi Tech steps into the operation, analyzes processes and data, implements improvements with artificial intelligence, business process automation and custom software, and follows the results. Tironi Tech Club is the ongoing way to do that. Custom development remains available when the scope needs a specific project.", items: [ { title: "Strategic clarity", text: "Understanding the business before any technical decision." }, { title: "Technical execution", text: "Organized, modern builds prepared to evolve." }, { title: "Digital product", text: "Solutions designed for real use, operation and growth." }, { title: "Continuous evolution", text: "Progressive improvements as the operation matures." } ] },
    experience: { eyebrow: "Premium structure", title: "A technology structure designed from diagnosis to evolution", description: "We work with scope clarity, product vision and technical execution to reduce risk, accelerate decisions and deliver sustainable digital solutions.", pills: ["Diagnosis", "Strategy", "Design and experience", "Development", "Integrations", "Evolution"], cards: [ { tag: "Diagnosis", title: "Deep understanding", text: "We map processes, bottlenecks, goals and business priorities." }, { tag: "Strategy", title: "Solution with direction", text: "We define the best digital path considering impact and feasibility." }, { tag: "Product", title: "Organized experience", text: "We design flows, interfaces and journeys that make use easier." }, { tag: "Evolution", title: "Continuous growth", text: "We support improvements, integrations and new needs." } ] },
    solutions: { eyebrow: "Execution capabilities", title: "Technology joins when it speeds up the result", items: [ { title: "Custom software", text: "Personalized systems to solve specific company flows, organize data, reduce manual work and improve operations." }, { title: "Websites and digital platforms", text: "Institutional websites, landing pages, dashboards, portals and platforms focused on presence, clarity and conversion." }, { title: "Process automation", text: "Automation of routines, integrations, internal flows and repetitive tasks to increase productivity and reduce errors." }, { title: "AI applied to business", text: "Artificial intelligence for service, analysis, data organization, decision support and process optimization." }, { title: "Integrations and APIs", text: "Connection between systems, databases, external services, payments, CRMs and operational tools." }, { title: "Evolution and maintenance", text: "Continuous improvements, fixes, performance, new features and technical support." } ] },
    chatbo: { eyebrow: "CHATBÔ • SALES AI", title: "Turn conversations into sales opportunities with AI", description: "Centralize your channels, qualify leads at any time and track every opportunity in a workspace designed to help sales teams move faster.", features: [ { title: "Omnichannel service", text: "WhatsApp, Instagram, Facebook, Telegram, WebChat and email in one operation." }, { title: "AI qualification", text: "The agent handles triage, organizes context and prepares opportunities for your team." }, { title: "Pipeline and recovery", text: "Track negotiations, follow-ups and stalled leads without scattered controls." }, { title: "AI working with people", text: "Response suggestions speed up service while your team stays in control." } ], primaryCta: "Try it free for 5 days", secondaryCta: "See how it works", trustLabel: "Trial conditions", trust: ["No credit card", "Training included", "Human support"], status: "AI + TEAM ONLINE", channelsLabel: "Integrated channels", channels: ["WhatsApp", "Instagram", "WebChat", "Email"], imageAlt: "ChatBô sales workspace with conversations, opportunities and AI assistance" },
    featuredProjects: { eyebrow: "Results", title: "Execution that already became an operation", description: "See the context, the solution built and the capabilities delivered in TironiTech projects.", caseLabels: { solution: "Solution built", impact: "Capabilities delivered" }, items: [ { tag: "Cybersecurity / Web3", title: "SignGuard", description: "A solution focused on clarity and protection for crypto wallet interactions, helping users understand connections, signatures, approvals and transactions before confirmation.", bullets: ["More clarity for users", "Greater perceived security", "Premium visual layer", "Strong product positioning"], cta: "View project" }, { tag: "Compliance / Privacy Tech", title: "DeleteActPro", description: "Platform oriented to compliance automation for California DROP / SB 362, with ingestion flow, evidence, cascade deletions and audit-ready records.", bullets: ["Regulatory automation", "Auditable structure", "Scalable operation", "Enterprise positioning"], cta: "Explore solution" }, { tag: "Raffles / Digital Platform", title: "Sorteios NewStore", description: "Digital platform for managing raffles, reservations, buyers, payments and administrative operations, focused on clarity, control and user experience.", bullets: ["Raffle management", "Reservations and buyers", "Admin dashboard", "Scalable operation"], cta: "Explore solution" } , { tag: "EdTech / Sales Simulator", title: "Sales Game", description: "A commercial strategy game built for Casagrande Consultoria and Multiplier, with local and online matches covering cash, customers, teams, channels, ERP, training and market events.", bullets: ["Website and Google Play", "Multiplayer and local play", "Commercial management", "Responsive experience"], cta: "Play Sales Game" }, { tag: "Raffles / E-commerce", title: "Sorteios xNaMai", description: "A raffle platform integrated with the xNaMai experience, including number selection, participant accounts, credit rules and campaign tracking.", bullets: ["Number selection", "Participant accounts", "Integrated credits", "Responsive operation"], cta: "View platform" }, { tag: "Subscription Tech / Benefits Club", title: "XNaMai Club", description: "A business subscription platform built to turn commercial benefits into a new recurring revenue stream, with plans, savings simulation, catalog and secure subscription management.", bullets: ["R$ 200K in recurring revenue", "Plans and recurring billing", "Savings simulator", "Secure subscription journey"], cta: "Explore project" }, { tag: "Sales Tech / Outreach", title: "MestreLead", description: "An email prospecting product with campaigns, templates, contacts, CRM, send queue, reports and lead database ingestion in one commercial operation.", bullets: ["Email campaigns", "Integrated CRM", "Queue and reports", "Lead ingestion"], cta: "Explore product" }, { tag: "Data / Business Intelligence", title: "BI Personalizado", description: "Custom BI dashboards for strategic clients, combining orders, products, buyers, retention, LTV, sales teams, inventory, logistics and data quality.", bullets: ["Custom indicators", "Commercial data", "Retention and LTV", "Monitored synchronization"], cta: "Build my BI" } , { tag: "AdTech / Shopify App", title: "ProfitPilot Ads", description: "A Shopify ads copilot connecting Meta, Google and TikTok, with a preflight checklist, budget guardrails and profit-first performance in one dashboard.", bullets: ["Shopify App", "Meta, Google and TikTok", "Budget protection", "Profit-first dashboard"], cta: "View product" } ] },
    impact: { eyebrow: "Business impact", title: "Technology that improves operations, sales and digital presence", description: "TironiTech structures technology to turn processes into operational advantage and digital presence into real growth.", items: [ { title: "More efficient operations", text: "Systems and automations reduce rework, organize data and make processes clearer." }, { title: "Sales enabled", text: "Pages, platforms and digital flows designed to improve conversion and customer relationships." }, { title: "Integrated processes", text: "We connect tools, APIs and databases to reduce manual tasks and centralize information." }, { title: "Stronger digital presence", text: "Professional digital experiences that increase authority, trust and perceived value." }, { title: "Clearer decisions", text: "Dashboards, reports and organized data to support growth and management." }, { title: "Continuous evolution", text: "Technology follows the operation as the business grows." } ] },
    process: { eyebrow: "How it works", title: "Analyze, prioritize, implement, measure and evolve", steps: [ { title: "Analyze", text: "We enter the operation and the data to see where time, money or control is lost." }, { title: "Prioritize", text: "We choose the front that most holds growth back." }, { title: "Implement", text: "We make the change through process, automation, integration or software." }, { title: "Measure", text: "We follow the agreed indicator, not only whether the task was delivered." }, { title: "Evolve", text: "The next month starts from what worked and what still blocks progress." } ] },
    whyChoose: { eyebrow: "Why choose TironiTech", title: "A strategic partner to structure technology with results", items: [ { title: "Consultative vision", text: "Technology is connected to business goals, not only to technical delivery." }, { title: "Lean execution", text: "We prioritize clarity, organization and decisions that reduce waste." }, { title: "Solid technical base", text: "Projects designed for stability, maintenance and evolution." }, { title: "Strong digital presence", text: "Solutions that communicate trust and increase perceived value." } ] },
    finalCta: { title: "Schedule a strategic diagnosis", description: "In one conversation we map what is holding growth back and what is worth implementing first. The Club is the ongoing path; a development project exists when the scope needs its own delivery." },
    footer: { text: "We step into the business, implement the change and follow the result.", navTitle: "Navigation", contactTitle: "Contact", whatsapp: "WhatsApp", cookiePreferences: "Cookie preferences", privacy: "Privacy Policy" },
    cookies: {
      label: "Cookie preferences",
      banner: "We use cookies to measure and improve your experience. You control non-essential cookies.",
      text: "TironiTech uses cookies to improve your experience, remember preferences and understand how the website is used. You can accept all, reject non-essential cookies or customize your choices.",
      privacy: "Privacy Policy",
      acceptAll: "Accept all",
      accept: "Accept all",
      reject: "Reject",
      preferences: "Preferences",
      savePreferences: "Save preferences",
      rejectNonEssential: "Reject non-essential",
      modalTitle: "Cookie preferences",
      modalText: "Manage how TironiTech can use cookies in your browser. Necessary cookies always remain active to keep the website working properly.",
      close: "Close cookie preferences",
      alwaysActive: "Always active",
      enabled: "Enabled",
      disabled: "Disabled",
      categories: {
        necessary: { title: "Necessary", description: "Essential for the basic operation of the website and cannot be disabled." },
        preferences: { title: "Preferences", description: "Help remember choices such as language and navigation settings." },
        analytics: { title: "Analytics", description: "Measure usage and performance and, when enabled, provide interaction maps and session recordings with sensitive fields masked." },
        marketing: { title: "Marketing", description: "May be used to measure campaigns, improve promotion and personalize communications." },
      },
    },
  },  es: {
    nav: { services: "Servicios", clients: "Clientes", systems: "Sistemas", projects: "Proyectos", contact: "Contacto", club: "Club", method: "Cómo funciona", tools: "Herramientas", development: "Desarrollo", results: "Resultados", insights: "Insights", cta: "Agendar diagnóstico", openMenu: "Abrir menú", closeMenu: "Cerrar menú", languageLabel: "Idioma" },
    hero: { eyebrow: "Tecnología con claridad, estructura y evolución", title: "Transformamos tecnología en crecimiento real para tu negocio", titleTop: "Transformamos tecnología", titleMiddle: "en crecimiento real", titleBottom: "para tu negocio", description: "Desarrollamos software a medida, automatizaciones, IA aplicada y plataformas digitales para empresas que necesitan organizar procesos, vender más y evolucionar con claridad.", primaryCta: "Iniciar proyecto", secondaryCta: "Conocer soluciones", bullets: ["Software a medida", "Automatización de procesos", "IA aplicada", "Crecimiento digital"], metrics: ["Operaciones más claras", "Procesos más inteligentes", "Presencia digital fortalecida"] },
    trustedBy: { title: "Empresas y proyectos que ya pasaron por TironiTech", description: "Creamos soluciones digitales, sitios institucionales, plataformas, automatizaciones y sistemas pensados para resolver problemas reales de operación y crecimiento." },
    about: { eyebrow: "Tironi Tech", title: "Transformación empresarial con ejecución", description: "Tironi Tech entra en la operación, analiza procesos y datos, implementa mejoras con inteligencia artificial, automatización de procesos empresariales y software a medida, y acompaña los resultados. Tironi Tech Club es la forma continua de hacerlo. El desarrollo a medida sigue disponible cuando el alcance pide un proyecto específico.", items: [ { title: "Claridad estratégica", text: "Entendimiento del negocio antes de cualquier decisión técnica." }, { title: "Ejecución técnica", text: "Construcción organizada, moderna y preparada para evolucionar." }, { title: "Producto digital", text: "Soluciones pensadas para uso real, operación y crecimiento." }, { title: "Evolución continua", text: "Mejoras progresivas conforme la operación madura." } ] },
    experience: { eyebrow: "Estructura premium", title: "Una estructura de tecnología pensada del diagnóstico a la evolución", description: "Trabajamos con claridad de alcance, visión de producto y ejecución técnica para reducir riesgos, acelerar decisiones y entregar soluciones digitales sostenibles.", pills: ["Diagnóstico", "Estrategia", "Diseño y experiencia", "Desarrollo", "Integraciones", "Evolución"], cards: [ { tag: "Diagnóstico", title: "Entendimiento profundo", text: "Mapeamos procesos, cuellos de botella, objetivos y prioridades del negocio." }, { tag: "Estrategia", title: "Solución con dirección", text: "Definimos el mejor camino digital considerando impacto y viabilidad." }, { tag: "Producto", title: "Experiencia organizada", text: "Diseñamos flujos, interfaces y recorridos para facilitar el uso." }, { tag: "Evolución", title: "Crecimiento continuo", text: "Acompañamos mejoras, integraciones y nuevas necesidades." } ] },
    solutions: { eyebrow: "Capacidades de ejecución", title: "La tecnología entra cuando acelera el resultado", items: [ { title: "Software a medida", text: "Sistemas personalizados para resolver flujos específicos de la empresa, organizar datos, reducir tareas manuales y mejorar la operación." }, { title: "Sitios y plataformas digitales", text: "Sitios institucionales, landing pages, dashboards, portales y plataformas con foco en presencia, claridad y conversión." }, { title: "Automatización de procesos", text: "Automatización de rutinas, integraciones, flujos internos y tareas repetitivas para aumentar productividad y reducir errores." }, { title: "IA aplicada al negocio", text: "Inteligencia artificial en atención, análisis, organización de datos, soporte a decisiones y optimización de procesos." }, { title: "Integraciones y APIs", text: "Conexión entre sistemas, bases de datos, servicios externos, pagos, CRMs y herramientas de operación." }, { title: "Evolución y mantenimiento", text: "Mejoras continuas, correcciones, performance, nuevas funcionalidades y acompañamiento técnico." } ] },
    chatbo: { eyebrow: "CHATBÔ • IA COMERCIAL", title: "Transforma conversaciones en oportunidades de venta con IA", description: "Centraliza tus canales, califica leads a cualquier hora y acompaña cada oportunidad en un entorno creado para dar velocidad al equipo comercial.", features: [ { title: "Atención multicanal", text: "WhatsApp, Instagram, Facebook, Telegram, WebChat y correo en una sola operación." }, { title: "Calificación con IA", text: "El agente realiza la clasificación, organiza el contexto y prepara oportunidades para el equipo." }, { title: "Embudo y recuperación", text: "Acompaña negociaciones, seguimientos y leads detenidos sin controles dispersos." }, { title: "IA junto a personas", text: "Las sugerencias de respuesta aceleran la atención mientras tu equipo mantiene el control." } ], primaryCta: "Probar gratis durante 5 días", secondaryCta: "Ver cómo funciona", trustLabel: "Condiciones de la prueba", trust: ["Sin tarjeta", "Capacitación incluida", "Soporte humano"], status: "IA + EQUIPO ONLINE", channelsLabel: "Canales integrados", channels: ["WhatsApp", "Instagram", "WebChat", "Correo"], imageAlt: "Panel comercial de ChatBô con conversaciones, oportunidades y asistencia de IA" },
    featuredProjects: { eyebrow: "Resultados", title: "Ejecución que ya se volvió operación", description: "Conoce el contexto, la solución construida y las capacidades entregadas en proyectos de TironiTech.", caseLabels: { solution: "Solución construida", impact: "Capacidades entregadas" }, items: [ { tag: "Cybersecurity / Web3", title: "SignGuard", description: "Solución enfocada en claridad y protección para interacciones con billeteras cripto, ayudando al usuario a entender conexiones, firmas, aprobaciones y transacciones antes de confirmar.", bullets: ["Más claridad para el usuario", "Más seguridad percibida", "Capa visual premium", "Producto con posicionamiento fuerte"], cta: "Ver proyecto" }, { tag: "Compliance / Privacy Tech", title: "DeleteActPro", description: "Plataforma orientada a la automatización de compliance para California DROP / SB 362, con flujo de ingestión, evidencias, eliminaciones en cascada y registros preparados para auditoría.", bullets: ["Automatización regulatoria", "Estructura auditable", "Operación escalable", "Posicionamiento enterprise"], cta: "Conocer solución" }, { tag: "Sorteos / Plataforma Digital", title: "Sorteios NewStore", description: "Plataforma digital para gestionar sorteos, reservas, compradores, pagos y operación administrativa, con foco en claridad, control y experiencia del usuario.", bullets: ["Gestión de sorteos", "Reservas y compradores", "Panel administrativo", "Operación escalable"], cta: "Conocer solución" } , { tag: "EdTech / Simulador Comercial", title: "Sales Game", description: "Juego de estrategia comercial desarrollado para Casagrande Consultoria y Multiplier, con partidas locales y online, decisiones de caja, clientes, equipo, canales, ERP, capacitación y eventos de mercado.", bullets: ["Sitio y Google Play", "Multiplayer y juego local", "Gestión comercial", "Experiencia responsiva"], cta: "Jugar Sales Game" }, { tag: "Sorteos / E-commerce", title: "Sorteios xNaMai", description: "Plataforma de sorteos integrada a la experiencia xNaMai, con selección de números, cuenta del participante, reglas de crédito y seguimiento de campaña.", bullets: ["Selección de números", "Cuenta del participante", "Créditos integrados", "Operación responsiva"], cta: "Ver plataforma" }, { tag: "Subscription Tech / Club de beneficios", title: "XNaMai Club", description: "Plataforma de suscripciones empresariales creada para convertir beneficios comerciales en una nueva fuente de ingresos recurrentes, con planes, simulador de ahorro, catálogo y gestión segura de la suscripción.", bullets: ["R$ 200 mil en ingresos recurrentes", "Planes y cobro recurrente", "Simulador de ahorro", "Experiencia de suscripción segura"], cta: "Conocer el proyecto" }, { tag: "Sales Tech / Outreach", title: "MestreLead", description: "Producto de prospección por correo con campañas, modelos, contactos, CRM, cola de envío, informes e ingestión de bases en una sola operación comercial.", bullets: ["Campañas de correo", "CRM integrado", "Cola e informes", "Ingestión de leads"], cta: "Conocer producto" }, { tag: "Data / Business Intelligence", title: "BI Personalizado", description: "Paneles de BI a medida para clientes estratégicos, reuniendo pedidos, productos, compradores, retención, LTV, vendedores, inventario, logística y calidad de datos.", bullets: ["Indicadores a medida", "Datos comerciales", "Retención y LTV", "Sincronización monitoreada"], cta: "Crear mi BI" } , { tag: "AdTech / Shopify App", title: "ProfitPilot Ads", description: "Copiloto de anuncios para Shopify que conecta Meta, Google y TikTok, aplica checklist previo, protege presupuesto con guardrails y muestra desempeño orientado a rentabilidad.", bullets: ["Shopify App", "Meta, Google y TikTok", "Protección de presupuesto", "Panel profit-first"], cta: "Ver producto" } ] },
    impact: { eyebrow: "Impacto para el negocio", title: "Tecnología que mejora operación, ventas y presencia digital", description: "TironiTech estructura tecnología para transformar procesos en ventaja operacional y presencia digital en crecimiento real.", items: [ { title: "Operación más eficiente", text: "Sistemas y automatizaciones reducen retrabajo, organizan datos y vuelven los procesos más claros." }, { title: "Ventas impulsadas", text: "Páginas, plataformas y flujos digitales pensados para mejorar conversión y relación con clientes." }, { title: "Procesos integrados", text: "Conectamos herramientas, APIs y bases de datos para disminuir tareas manuales y centralizar información." }, { title: "Presencia digital fortalecida", text: "Experiencias digitales profesionales que aumentan autoridad, confianza y percepción de valor." }, { title: "Decisiones con más claridad", text: "Dashboards, informes y datos organizados para apoyar crecimiento y gestión." }, { title: "Evolución continua", text: "La tecnología acompaña la operación a medida que el negocio crece." } ] },
    process: { eyebrow: "Cómo funciona", title: "Analizar, priorizar, implementar, medir y evolucionar", steps: [ { title: "Analizar", text: "Entramos en la operación y en los datos para ver dónde se pierde tiempo, dinero o control." }, { title: "Priorizar", text: "Elegimos el frente que más frena el crecimiento." }, { title: "Implementar", text: "Hacemos el cambio con proceso, automatización, integración o software." }, { title: "Medir", text: "Acompañamos el indicador acordado, no solo si la tarea se entregó." }, { title: "Evolucionar", text: "El mes siguiente parte de lo que funcionó y de lo que todavía traba." } ] },
    whyChoose: { eyebrow: "Por qué elegir TironiTech", title: "Una socia estratégica para estructurar tecnología con resultado", items: [ { title: "Visión consultiva", text: "La tecnología nace conectada al objetivo del negocio, no solo a la entrega técnica." }, { title: "Ejecución ágil", text: "Priorizamos claridad, organización y decisiones que reducen desperdicio." }, { title: "Base técnica sólida", text: "Proyectos pensados para estabilidad, mantenimiento y evolución." }, { title: "Presencia digital fuerte", text: "Soluciones que comunican confianza y aumentan percepción de valor." } ] },
    finalCta: { title: "Agenda un diagnóstico estratégico", description: "En una conversación mapeamos lo que frena el crecimiento y lo que conviene implementar primero. El Club es el camino continuo; un proyecto de desarrollo existe cuando el alcance pide una entrega propia." },
    footer: { text: "Entramos en el negocio, implementamos el cambio y acompañamos el resultado.", navTitle: "Navegación", contactTitle: "Contacto", whatsapp: "WhatsApp", cookiePreferences: "Preferencias de cookies", privacy: "Política de Privacidad" },
    cookies: {
      label: "Preferencias de cookies",
      banner: "Usamos cookies para medir y mejorar tu experiencia. Tú controlas las cookies no esenciales.",
      text: "TironiTech utiliza cookies para mejorar tu experiencia, recordar preferencias y entender cómo se utiliza el sitio. Puedes aceptar todos, rechazar cookies no esenciales o personalizar tus opciones.",
      privacy: "Política de Privacidad",
      acceptAll: "Aceptar todos",
      accept: "Aceptar todos",
      reject: "Rechazar",
      preferences: "Preferencias",
      savePreferences: "Guardar preferencias",
      rejectNonEssential: "Rechazar no esenciales",
      modalTitle: "Preferencias de cookies",
      modalText: "Gestiona cómo TironiTech puede usar cookies en tu navegador. Las cookies necesarias permanecen siempre activas para mantener el sitio funcionando correctamente.",
      close: "Cerrar preferencias de cookies",
      alwaysActive: "Siempre activo",
      enabled: "Activo",
      disabled: "Inactivo",
      categories: {
        necessary: { title: "Necesarias", description: "Esenciales para el funcionamiento básico del sitio y no se pueden desactivar." },
        preferences: { title: "Preferencias", description: "Ayudan a recordar opciones como idioma y configuraciones de navegación." },
        analytics: { title: "Analytics", description: "Miden el uso y el rendimiento y, cuando están habilitadas, permiten mapas de interacción y grabaciones de sesión con campos sensibles enmascarados." },
        marketing: { title: "Marketing", description: "Pueden usarse para medir campañas, mejorar la divulgación y personalizar comunicaciones." },
      },
    },
  },
};
