export const heroImpactOverrides = {
  pt: {
    brandTagline: "Transformação contínua",
    hero: {
      eyebrow: "TIRONI TECH CLUB · TRANSFORMAÇÃO CONTÍNUA",
      title: "Entramos no seu negócio para encontrar o que trava o crescimento — e fazer a mudança acontecer.",
      opening: "Entramos no seu negócio para encontrar o que trava o crescimento —",
      emphasis: "e fazer a mudança acontecer.",
      description: "Nosso time entra na operação, organiza o que importa, constrói o que falta e acompanha os indicadores mês a mês.",
      promise: "Nosso time entra na operação, organiza o que importa, constrói o que falta e acompanha os indicadores mês a mês.",
      primaryCta: "Agendar diagnóstico estratégico",
      secondaryCta: "Conhecer como o Club funciona",
      secondaryHref: "/como-funciona",
      reassurance: "Diagnóstico estratégico • conversa direta com a equipe",
      transformationLabel: "O QUE ACONTECE NO DIAGNÓSTICO",
      demoLabel: "Ciclo do Club",
      demoKicker: "TIRONI TECH CLUB",
      demoTitle: "A operação, mês a mês",
      demoStatus: "Em andamento",
      demoFooter: "Todo mês",
      demoGain: "Evoluir",
      cycle: ["ANALISAR", "PRIORIZAR", "IMPLEMENTAR", "MEDIR", "EVOLUIR"],
      transformations: [
        { pain: "Clareza", outcome: "Diagnóstico + prioridades orientadas por dados" },
        { pain: "Execução", outcome: "Implementação + acompanhamento contínuo" },
      ],
      authority: [
        { value: "23+", label: "anos de experiência acumulada" },
        { value: "150+", label: "projetos para empresas" },
        { value: "50+", label: "soluções e projetos próprios" },
        { value: "3", label: "frentes de impacto: vendas, processos e operação" },
      ],
      panel: {
        title: "Operação digital estruturada",
        items: ["Processos integrados", "Vendas impulsionadas", "Presença digital fortalecida", "Automação inteligente"],
      },
    },
    trustedBy: {
      title: "Empresas que confiam na TironiTech",
      description: "Projetos, parceiros e soluções conectados à nossa tecnologia.",
      items: ["SignGuard", "DeleteActPro", "Sorteios NewStore", "TironiTech", "SalesGame", "Sites institucionais", "Plataformas digitais", "Automações", "Sistemas internos", "Landing pages"],
    },
    experienceProof: {
      title: "Experiência aplicada em soluções que geram resultado",
      text: "A TironiTech cria softwares, automações e plataformas digitais para organizar processos, integrar operações e acelerar o crescimento de empresas com mais clareza e eficiência.",
      metrics: [
        { value: "23+", label: "anos de experiência acumulada" },
        { value: "150+", label: "projetos para empresas" },
        { value: "50+", label: "soluções e projetos próprios" },
        { value: "3", label: "frentes de impacto: vendas, processos e operação" },
      ],
      points: ["Diagnóstico orientado ao negócio", "Tecnologia conectada a vendas e operação", "Evolução contínua de produtos digitais"],
    },
  },
  en: {
    brandTagline: "Continuous transformation",
    hero: {
      eyebrow: "TIRONI TECH CLUB · CONTINUOUS TRANSFORMATION",
      title: "We step into your business to find what is holding growth back — and make the change happen.",
      opening: "We step into your business to find what is holding growth back —",
      emphasis: "and make the change happen.",
      description: "Our team steps into the operation, organizes what matters, builds what is missing and follows the indicators month after month.",
      promise: "Our team steps into the operation, organizes what matters, builds what is missing and follows the indicators month after month.",
      primaryCta: "Schedule a strategic diagnosis",
      secondaryCta: "See how the Club works",
      secondaryHref: "/como-funciona",
      reassurance: "Strategic diagnosis • direct conversation with the team",
      transformationLabel: "WHAT THE DIAGNOSIS COVERS",
      demoLabel: "Club cycle",
      demoKicker: "TIRONI TECH CLUB",
      demoTitle: "The operation, month by month",
      demoStatus: "In progress",
      demoFooter: "Every month",
      demoGain: "Evolve",
      cycle: ["ANALYZE", "PRIORITIZE", "IMPLEMENT", "MEASURE", "EVOLVE"],
      transformations: [
        { pain: "Clarity", outcome: "Diagnosis + priorities guided by data" },
        { pain: "Execution", outcome: "Implementation + ongoing follow-up" },
      ],
      authority: [
        { value: "23+", label: "years of combined experience" },
        { value: "150+", label: "business projects" },
        { value: "50+", label: "proprietary solutions and products" },
        { value: "3", label: "impact areas: sales, processes and operations" },
      ],
      panel: {
        title: "Structured digital operation",
        items: ["Integrated processes", "Sales enabled", "Stronger digital presence", "Intelligent automation"],
      },
    },
    trustedBy: {
      title: "Companies that trust TironiTech",
      description: "Projects, partners and solutions connected to our technology.",
      items: ["SignGuard", "DeleteActPro", "Sorteios NewStore", "TironiTech", "SalesGame", "Institutional websites", "Digital platforms", "Automations", "Internal systems", "Landing pages"],
    },
    experienceProof: {
      title: "Experience applied to solutions that generate results",
      text: "TironiTech builds software, automations and digital platforms to organize processes, integrate operations and accelerate business growth with clarity and efficiency.",
      metrics: [
        { value: "23+", label: "years of combined experience" },
        { value: "150+", label: "business projects" },
        { value: "50+", label: "proprietary solutions and products" },
        { value: "3", label: "impact areas: sales, processes and operations" },
      ],
      points: ["Business-oriented diagnosis", "Technology connected to sales and operations", "Continuous evolution of digital products"],
    },
  },
  es: {
    brandTagline: "Transformación continua",
    hero: {
      eyebrow: "TIRONI TECH CLUB · TRANSFORMACIÓN CONTINUA",
      title: "Entramos en tu negocio para encontrar lo que frena el crecimiento — y hacer que el cambio ocurra.",
      opening: "Entramos en tu negocio para encontrar lo que frena el crecimiento —",
      emphasis: "y hacer que el cambio ocurra.",
      description: "Nuestro equipo entra en la operación, organiza lo que importa, construye lo que falta y acompaña los indicadores mes a mes.",
      promise: "Nuestro equipo entra en la operación, organiza lo que importa, construye lo que falta y acompaña los indicadores mes a mes.",
      primaryCta: "Agendar diagnóstico estratégico",
      secondaryCta: "Conocer cómo funciona el Club",
      secondaryHref: "/como-funciona",
      reassurance: "Diagnóstico estratégico • conversación directa con el equipo",
      transformationLabel: "QUÉ CUBRE EL DIAGNÓSTICO",
      demoLabel: "Ciclo del Club",
      demoKicker: "TIRONI TECH CLUB",
      demoTitle: "La operación, mes a mes",
      demoStatus: "En curso",
      demoFooter: "Cada mes",
      demoGain: "Evolucionar",
      cycle: ["ANALIZAR", "PRIORIZAR", "IMPLEMENTAR", "MEDIR", "EVOLUCIONAR"],
      transformations: [
        { pain: "Claridad", outcome: "Diagnóstico + prioridades orientadas por datos" },
        { pain: "Ejecución", outcome: "Implementación + seguimiento continuo" },
      ],
      authority: [
        { value: "23+", label: "años de experiencia acumulada" },
        { value: "150+", label: "proyectos para empresas" },
        { value: "50+", label: "soluciones y proyectos propios" },
        { value: "3", label: "áreas de impacto: ventas, procesos y operación" },
      ],
      panel: {
        title: "Operación digital estructurada",
        items: ["Procesos integrados", "Ventas impulsadas", "Presencia digital fortalecida", "Automatización inteligente"],
      },
    },
    trustedBy: {
      title: "Empresas que confían en TironiTech",
      description: "Proyectos, socios y soluciones conectados a nuestra tecnología.",
      items: ["SignGuard", "DeleteActPro", "Sorteios NewStore", "TironiTech", "SalesGame", "Sitios institucionales", "Plataformas digitales", "Automatizaciones", "Sistemas internos", "Landing pages"],
    },
    experienceProof: {
      title: "Experiencia aplicada en soluciones que generan resultados",
      text: "TironiTech crea software, automatizaciones y plataformas digitales para organizar procesos, integrar operaciones y acelerar el crecimiento de empresas con más claridad y eficiencia.",
      metrics: [
        { value: "23+", label: "años de experiencia acumulada" },
        { value: "150+", label: "proyectos para empresas" },
        { value: "50+", label: "soluciones y proyectos propios" },
        { value: "3", label: "áreas de impacto: ventas, procesos y operación" },
      ],
      points: ["Diagnóstico orientado al negocio", "Tecnología conectada a ventas y operación", "Evolución continua de productos digitales"],
    },
  },
};
