export const heroImpactOverrides = {
  pt: {
    brandTagline: "Tecnologia com clareza, estrutura e evolução",
    hero: {
      eyebrow: "SOFTWARE • AUTOMAÇÃO • IA",
      title: "Sua empresa cresceu. O caos operacional também?",
      opening: "Sua empresa cresceu.",
      emphasis: "O caos operacional também?",
      description: "Planilhas demais. Sistemas que não conversam. Clientes esperando resposta. Sua equipe perde tempo no que a tecnologia já pode resolver.",
      promise: "Software, automação e IA para eliminar retrabalho, conectar sua operação e devolver tempo ao seu time.",
      primaryCta: "Quero destravar minha operação",
      secondaryCta: "Ver o que podemos resolver",
      reassurance: "O primeiro passo é entender onde sua operação trava.",
      transformationLabel: "MENOS ATRITO. MAIS ESPAÇO PARA CRESCER.",
      transformations: [
        { pain: "Retrabalho todo dia", outcome: "Processos automatizados" },
        { pain: "Informação espalhada", outcome: "Sistemas conectados" },
        { pain: "Clientes esperando", outcome: "Atendimento com IA" },
      ],
      authority: [
        { value: "30+", label: "anos de experiência acumulada" },
        { value: "150+", label: "projetos para empresas" },
        { value: "50+", label: "soluções e projetos próprios" },
        { value: "3", label: "frentes de impacto: vendas, processos e operação" },
      ],
      panel: {
        title: "Operação digital estruturada",
        items: ["Processos integrados", "Vendas impulsionadas", "Presença digital fortalecida", "Automação inteligente"],
      },
    },
    trustedBy: {
      title: "Empresas que confiam na TironiTech",
      description: "Projetos, parceiros e soluções conectados à nossa tecnologia.",
      items: ["SignGuard", "DeleteActPro", "Sorteios NewStore", "TironiTech", "SalesGame", "Sites institucionais", "Plataformas digitais", "Automações", "Sistemas internos", "Landing pages"],
    },
    experienceProof: {
      title: "Experiência aplicada em soluções que geram resultado",
      text: "A TironiTech cria softwares, automações e plataformas digitais para organizar processos, integrar operações e acelerar o crescimento de empresas com mais clareza e eficiência.",
      metrics: [
        { value: "30+", label: "anos de experiência acumulada" },
        { value: "150+", label: "projetos para empresas" },
        { value: "50+", label: "soluções e projetos próprios" },
        { value: "3", label: "frentes de impacto: vendas, processos e operação" },
      ],
      points: ["Diagnóstico orientado ao negócio", "Tecnologia conectada a vendas e operação", "Evolução contínua de produtos digitais"],
    },
  },
  en: {
    brandTagline: "Technology with clarity, structure and evolution",
    hero: {
      eyebrow: "SOFTWARE • AUTOMATION • AI",
      title: "Your business grew. Did the operational chaos grow too?",
      opening: "Your business grew.",
      emphasis: "Did the chaos grow too?",
      description: "Too many spreadsheets. Disconnected systems. Customers waiting for answers. Your team spends time on work technology can already handle.",
      promise: "Software, automation and AI to eliminate repetitive work, connect your operations and give your team time back.",
      primaryCta: "Unblock my operations",
      secondaryCta: "See what we can solve",
      reassurance: "The first step is understanding where your operations get stuck.",
      transformationLabel: "LESS FRICTION. MORE ROOM TO GROW.",
      transformations: [
        { pain: "Daily repetitive work", outcome: "Automated processes" },
        { pain: "Scattered information", outcome: "Connected systems" },
        { pain: "Customers waiting", outcome: "AI-powered service" },
      ],
      authority: [
        { value: "30+", label: "years of combined experience" },
        { value: "150+", label: "business projects" },
        { value: "50+", label: "proprietary solutions and products" },
        { value: "3", label: "impact areas: sales, processes and operations" },
      ],
      panel: {
        title: "Structured digital operation",
        items: ["Integrated processes", "Sales enabled", "Stronger digital presence", "Intelligent automation"],
      },
    },
    trustedBy: {
      title: "Companies that trust TironiTech",
      description: "Projects, partners and solutions connected to our technology.",
      items: ["SignGuard", "DeleteActPro", "Sorteios NewStore", "TironiTech", "SalesGame", "Institutional websites", "Digital platforms", "Automations", "Internal systems", "Landing pages"],
    },
    experienceProof: {
      title: "Experience applied to solutions that generate results",
      text: "TironiTech builds software, automations and digital platforms to organize processes, integrate operations and accelerate business growth with clarity and efficiency.",
      metrics: [
        { value: "30+", label: "years of combined experience" },
        { value: "150+", label: "business projects" },
        { value: "50+", label: "proprietary solutions and products" },
        { value: "3", label: "impact areas: sales, processes and operations" },
      ],
      points: ["Business-oriented diagnosis", "Technology connected to sales and operations", "Continuous evolution of digital products"],
    },
  },
  es: {
    brandTagline: "Tecnología con claridad, estructura y evolución",
    hero: {
      eyebrow: "SOFTWARE • AUTOMATIZACIÓN • IA",
      title: "Tu empresa creció. ¿El caos operativo también?",
      opening: "Tu empresa creció.",
      emphasis: "¿El caos operativo también?",
      description: "Demasiadas hojas de cálculo. Sistemas desconectados. Clientes esperando respuestas. Tu equipo pierde tiempo en lo que la tecnología ya puede resolver.",
      promise: "Software, automatización e IA para eliminar tareas repetitivas, conectar tu operación y devolverle tiempo a tu equipo.",
      primaryCta: "Quiero desbloquear mi operación",
      secondaryCta: "Ver qué podemos resolver",
      reassurance: "El primer paso es entender dónde se atasca tu operación.",
      transformationLabel: "MENOS FRICCIÓN. MÁS ESPACIO PARA CRECER.",
      transformations: [
        { pain: "Trabajo repetitivo diario", outcome: "Procesos automatizados" },
        { pain: "Información dispersa", outcome: "Sistemas conectados" },
        { pain: "Clientes esperando", outcome: "Atención con IA" },
      ],
      authority: [
        { value: "30+", label: "años de experiencia acumulada" },
        { value: "150+", label: "proyectos para empresas" },
        { value: "50+", label: "soluciones y proyectos propios" },
        { value: "3", label: "áreas de impacto: ventas, procesos y operación" },
      ],
      panel: {
        title: "Operación digital estructurada",
        items: ["Procesos integrados", "Ventas impulsadas", "Presencia digital fortalecida", "Automatización inteligente"],
      },
    },
    trustedBy: {
      title: "Empresas que confían en TironiTech",
      description: "Proyectos, socios y soluciones conectados a nuestra tecnología.",
      items: ["SignGuard", "DeleteActPro", "Sorteios NewStore", "TironiTech", "SalesGame", "Sitios institucionales", "Plataformas digitales", "Automatizaciones", "Sistemas internos", "Landing pages"],
    },
    experienceProof: {
      title: "Experiencia aplicada en soluciones que generan resultados",
      text: "TironiTech crea software, automatizaciones y plataformas digitales para organizar procesos, integrar operaciones y acelerar el crecimiento de empresas con más claridad y eficiencia.",
      metrics: [
        { value: "30+", label: "años de experiencia acumulada" },
        { value: "150+", label: "proyectos para empresas" },
        { value: "50+", label: "soluciones y proyectos propios" },
        { value: "3", label: "áreas de impacto: ventas, procesos y operación" },
      ],
      points: ["Diagnóstico orientado al negocio", "Tecnología conectada a ventas y operación", "Evolución continua de productos digitales"],
    },
  },
};
