const whatsapp = 'https://wa.me/5543996676633?text=Ol%C3%A1%2C%20quero%20agendar%20um%20diagn%C3%B3stico%20com%20a%20Tironi%20Tech.';

const commonProcess = [
  ['Diagnóstico', 'Mapeamos o processo, os sistemas, os dados e o resultado comercial esperado.'],
  ['Prova controlada', 'Validamos o ponto de maior risco com dados reais e critérios de sucesso definidos.'],
  ['Implantação', 'Integramos a solução à operação, com permissões, testes e transferência para a equipe.'],
  ['Evolução', 'Acompanhamos indicadores e priorizamos melhorias a partir do uso real.'],
];

export const serviceLandingPages = [
  {
    slug: 'empresa-automacao-com-ia', keyword: 'Empresa de automação com IA',
    title: 'Automação com IA que reduz trabalho manual e move o processo até o resultado',
    description: 'A Tironi Tech identifica gargalos, integra sistemas e cria automações com IA para atendimento, vendas e operação, com controle humano e indicadores.',
    problem: 'Sua equipe copia dados, responde as mesmas perguntas e depende de planilhas para manter a operação em movimento.',
    outcomes: ['Menos tarefas repetitivas e retrabalho', 'Processos conectados a CRM, ERP e APIs', 'Decisões e exceções registradas para auditoria'],
    solution: 'Combinamos regras, integrações e agentes de IA. A automação interpreta informações variáveis, executa apenas ações autorizadas e encaminha exceções para a pessoa certa.',
    proof: '23+ anos de experiência acumulada em tecnologia e mais de 150 projetos ajudam a transformar uma ideia de automação em uma operação que pode ser acompanhada e evoluída.',
    image: '/brand/tironi-symbol.png', imageAlt: 'Símbolo Tironi Tech', process: commonProcess,
    faqs: [['O que uma empresa de automação com IA entrega?', 'Diagnóstico, desenho do fluxo, integrações, agentes, testes, implantação, monitoramento e evolução.'], ['É preciso trocar os sistemas atuais?', 'Na maioria dos projetos, não. A automação pode conectar CRM, ERP, WhatsApp e bases existentes por APIs.'], ['Como começar com menor risco?', 'Escolha um processo frequente, mensurável e com exceções conhecidas para uma prova controlada.']],
  },
  {
    slug: 'software-sob-medida', keyword: 'Software sob medida',
    title: 'Software sob medida para eliminar os limites que travam sua operação',
    description: 'Sistemas personalizados, portais e plataformas integradas ao processo da empresa, com arquitetura preparada para evoluir e incorporar IA.',
    problem: 'Ferramentas genéricas obrigam sua equipe a adaptar o processo, manter controles paralelos e aceitar integrações incompletas.',
    outcomes: ['Fluxos desenhados para a rotina real', 'Dados centralizados e acessíveis com segurança', 'Evolução do sistema conforme o negócio cresce'],
    solution: 'A Tironi Tech transforma regras, jornadas e integrações em um produto digital próprio. O projeto começa no problema operacional e termina com software testado, documentado e utilizável.',
    proof: 'Projetos em vendas, gestão, atendimento e operação deram à equipe repertório para equilibrar velocidade, segurança, experiência e custo total.',
    image: '/projects/sign-wallet-logo.png', imageAlt: 'Projeto de software desenvolvido pela Tironi Tech', process: commonProcess,
    faqs: [['Quando software sob medida vale a pena?', 'Quando diferenciação, integração, governança ou escala não cabem bem em um produto pronto.'], ['A Tironi Tech também mantém o sistema?', 'Sim. O modelo prevê monitoramento, correções e evolução por ciclos priorizados.'], ['É possível começar por um MVP?', 'Sim. O MVP valida a jornada essencial sem antecipar toda a complexidade do produto final.']],
  },
  {
    slug: 'empresa-inteligencia-artificial', keyword: 'Empresa de inteligência artificial',
    title: 'Inteligência artificial aplicada ao trabalho real da sua empresa',
    description: 'Agentes, busca em conhecimento, análise de documentos e automações conectadas aos sistemas da empresa, com governança e metas de negócio.',
    problem: 'A empresa testa ferramentas de IA isoladas, mas não consegue transformar experimentos em capacidade operacional confiável.',
    outcomes: ['Casos de uso priorizados por valor e risco', 'IA conectada a dados e ferramentas autorizadas', 'Qualidade, custo e intervenção humana monitorados'],
    solution: 'Projetamos a arquitetura completa: conhecimento, modelos, permissões, integrações, avaliação e experiência do usuário. Cada solução nasce com limites explícitos e um indicador de resultado.',
    proof: 'A Tironi Tech reúne desenvolvimento de software, automação e IA aplicada para evitar projetos que demonstram tecnologia sem resolver o processo.',
    image: '/brand/tironi-symbol.png', imageAlt: 'Tecnologia e inteligência artificial da Tironi Tech', process: commonProcess,
    faqs: [['Que tipos de solução com IA são possíveis?', 'Agentes, classificação, extração de documentos, busca com RAG, atendimento e apoio a decisões, entre outros.'], ['A IA pode acessar dados internos?', 'Sim, com autenticação, permissões, filtros, logs e fontes definidas para cada caso.'], ['Como medir a qualidade?', 'Com conjuntos de teste, revisão de falhas, métricas por segmento e indicadores do processo completo.']],
  },
  {
    slug: 'consultoria-ia-para-empresas', keyword: 'Consultoria de IA para empresas',
    title: 'Da dúvida sobre IA a um plano executável, priorizado e mensurável',
    description: 'Consultoria de IA para empresas que precisam escolher casos de uso, organizar dados, avaliar riscos e conduzir uma implantação com resultado.',
    problem: 'Há muitas ideias, fornecedores e ferramentas, mas pouca clareza sobre onde começar, quanto investir e como provar retorno.',
    outcomes: ['Mapa de oportunidades e dependências', 'Priorização por impacto, viabilidade e risco', 'Roadmap com responsáveis, métricas e próximos testes'],
    solution: 'Entrevistamos áreas, observamos processos e transformamos oportunidades em hipóteses testáveis. O plano inclui arquitetura, dados, segurança, adoção e critérios de continuidade.',
    proof: 'A consultoria é conduzida por quem também implementa. Isso aproxima recomendação e realidade técnica, reduzindo planos que não sobrevivem ao primeiro teste.',
    image: '/brand/tironi-symbol.png', imageAlt: 'Consultoria Tironi Tech para empresas', process: commonProcess,
    faqs: [['A consultoria termina em um relatório?', 'Não. A entrega inclui decisões, backlog, arquitetura de referência e desenho da primeira prova.'], ['Serve para pequenas e médias empresas?', 'Sim. O escopo é ajustado à maturidade, ao orçamento e ao risco da operação.'], ['Vocês podem implementar o plano?', 'Sim. A Tironi Tech pode seguir da prova de conceito à produção e evolução.']],
  },
  {
    slug: 'agentes-de-ia-para-empresas', keyword: 'Agentes de IA para empresas',
    title: 'Agentes de IA que consultam, decidem e agem dentro de limites claros',
    description: 'Desenvolvimento de agentes de IA conectados a documentos, CRM, ERP, APIs e equipes humanas para atendimento, vendas e processos internos.',
    problem: 'Um chatbot que apenas conversa não resolve tarefas que dependem de consultar dados, aplicar regras e registrar uma ação.',
    outcomes: ['Respostas baseadas em fontes autorizadas', 'Ações limitadas por função e permissão', 'Histórico, confirmação e encaminhamento humano'],
    solution: 'Cada ferramenta do agente executa uma função pequena e previsível. Identidade, autorização, memória, observabilidade e avaliação são tratadas como partes do produto.',
    proof: 'A experiência da Tironi Tech em sistemas e integrações permite construir o caminho completo entre a pergunta e o resultado operacional.',
    image: '/brand/chatbo/chatbo-interface.webp', imageAlt: 'Interface de agente de IA para empresas', process: commonProcess,
    faqs: [['Qual é a diferença entre agente e chatbot?', 'O agente pode usar ferramentas autorizadas para consultar ou executar ações; o chatbot pode se limitar à conversa.'], ['O agente substitui a equipe?', 'Ele assume tarefas delimitadas e transfere exceções, negociações e casos sensíveis com contexto.'], ['Como impedir ações indevidas?', 'Com menor privilégio, validação de parâmetros, confirmações, logs e aprovação humana em operações críticas.']],
  },
  {
    slug: 'agente-ia-whatsapp', keyword: 'Agente de IA para WhatsApp',
    title: 'Um agente de IA no WhatsApp que atende e ajuda a venda a avançar',
    description: 'ChatBô conecta conversa, catálogo, qualificação, CRM e atendimento humano para responder com contexto e transformar mensagens em próximos passos.',
    problem: 'Leads esperam, repetem informações e abandonam a conversa enquanto a equipe procura dados em sistemas diferentes.',
    outcomes: ['Atendimento disponível nos horários definidos', 'Qualificação e distribuição de oportunidades', 'Consulta a produtos, pedidos e informações autorizadas'],
    solution: 'O ChatBô entende a intenção, busca a fonte correta, conduz perguntas essenciais e registra o contexto. Quando necessário, entrega a conversa a uma pessoa sem recomeçar o atendimento.',
    proof: 'A solução é desenhada ao redor do funil e das regras da empresa, em vez de impor um roteiro genérico que não conversa com a operação.',
    image: '/brand/chatbo/chatbo-composition.png', imageAlt: 'ChatBô, agente de IA para WhatsApp', process: commonProcess,
    faqs: [['O agente consulta meus produtos?', 'Sim. Pode consultar catálogo, disponibilidade, regras e outras fontes por integração autorizada.'], ['Integra com CRM?', 'Sim. Pode identificar clientes, criar oportunidades, registrar resumos e atualizar etapas conforme as regras.'], ['O humano consegue assumir?', 'Sim. A transferência preserva dados, resumo e motivo para reduzir repetição.']],
  },
  {
    slug: 'automacao-whatsapp-com-ia', keyword: 'Automação de WhatsApp com IA',
    title: 'Automação de WhatsApp com IA sem perder contexto, controle ou humanidade',
    description: 'Automatize atendimento, qualificação, consultas e acompanhamento no WhatsApp com o ChatBô integrado à operação comercial.',
    problem: 'Respostas rápidas não bastam quando o cliente precisa de informação correta, continuidade e uma ação concreta.',
    outcomes: ['Menor tempo até a primeira resposta útil', 'Padronização sem conversas engessadas', 'Continuidade entre automação e equipe humana'],
    solution: 'Desenhamos intenções, fontes, limites, integrações e pontos de transferência. O fluxo combina linguagem natural com regras de negócio e registra o que aconteceu.',
    proof: 'O ChatBô une produto e personalização: uma base pronta para WhatsApp com implantação ajustada ao processo de cada empresa.',
    image: '/brand/chatbo/chatbo-panel.png', imageAlt: 'Painel de automação de WhatsApp com IA', process: commonProcess,
    faqs: [['A automação usa a API oficial?', 'A implantação considera os canais e provedores oficiais adequados ao cenário.'], ['É possível manter o número atual?', 'Depende da configuração e do provedor; isso é validado no diagnóstico.'], ['Como evitar respostas inventadas?', 'Limitamos fontes, ferramentas e escopo, além de testar e encaminhar casos de baixa confiança.']],
  },
  {
    slug: 'desenvolvimento-software-sob-medida', keyword: 'Desenvolvimento de software sob medida',
    title: 'Desenvolvimento de software sob medida com produto, engenharia e IA no mesmo plano',
    description: 'Da descoberta ao lançamento: aplicações web, SaaS, portais, sistemas empresariais e integrações construídos para uma necessidade específica.',
    problem: 'Projetos atrasam quando requisitos viram uma lista de telas sem prioridade, validação com usuários ou estratégia de evolução.',
    outcomes: ['Escopo organizado por jornadas e valor', 'Arquitetura compatível com segurança e crescimento', 'Entregas progressivas com demonstrações e critérios de aceite'],
    solution: 'Trabalhamos em ciclos curtos: entendimento, protótipo, implementação, demonstração e aprendizado. IA entra onde melhora o produto ou acelera o processo com qualidade verificável.',
    proof: 'Mais de 150 projetos e 23+ anos de experiência acumulada sustentam decisões técnicas ligadas à realidade do negócio.',
    image: '/projects/deleteactpro-logo.png', imageAlt: 'Produto digital desenvolvido sob medida', process: commonProcess,
    faqs: [['Quanto tempo leva?', 'Depende do menor produto completo. O diagnóstico transforma a ideia em etapas e reduz a incerteza antes da estimativa.'], ['Quem é dono do código e dos dados?', 'Esses pontos são definidos em contrato; a solução deve preservar acesso e portabilidade do cliente.'], ['É possível integrar IA depois?', 'Sim, quando arquitetura, dados e permissões são preparados para evolução.']],
  },
  {
    slug: 'automacao-processos-com-ia', keyword: 'Automação de processos com IA',
    title: 'Automação de processos com IA para transformar filas, documentos e exceções em fluxo',
    description: 'Mapeamento e automação de processos empresariais que combinam regras, IA, integrações e revisão humana para reduzir ciclo e erro.',
    problem: 'O processo fica preso entre e-mails, documentos, aprovações, planilhas e sistemas que não compartilham contexto.',
    outcomes: ['Entrada e classificação padronizadas', 'Aprovações e exceções encaminhadas com contexto', 'Indicadores de tempo, falha e resultado por etapa'],
    solution: 'Modelamos eventos, estados e responsabilidades. A IA trata informações variáveis; regras controlam decisões estáveis; integrações executam e registram ações.',
    proof: 'A Tironi Tech avalia o processo completo para evitar automações locais que apenas deslocam o trabalho para outra etapa.',
    image: '/brand/tironi-symbol.png', imageAlt: 'Automação de processos empresariais com IA', process: commonProcess,
    faqs: [['Quais processos são melhores para começar?', 'Os frequentes, mensuráveis, baseados em informação e com exceções conhecidas.'], ['Automação com IA é segura?', 'Pode ser, quando identidade, permissão, validação, logs e supervisão são projetados desde o início.'], ['Como calcular retorno?', 'Compare tempo, custo, erro, ciclo e resultado antes e depois, incluindo implantação e operação.']],
  },
  {
    slug: 'desenvolvimento-solucoes-com-ia', keyword: 'Desenvolvimento de soluções com IA',
    title: 'Soluções com IA construídas para gerar resultado além da demonstração',
    description: 'Desenvolvimento de produtos e capacidades com IA: agentes, RAG, análise de documentos, copilotos, automação e integrações empresariais.',
    problem: 'Uma prova impressionante pode falhar em produção por dados ruins, ausência de avaliação, custo imprevisível ou falta de integração.',
    outcomes: ['Hipótese de negócio e métrica definidas', 'Arquitetura com modelos e fornecedores substituíveis', 'Avaliação contínua de qualidade, custo e risco'],
    solution: 'Construímos o menor fluxo completo: entrada, interpretação, decisão, ação, exceção e registro. Depois ampliamos com evidências do piloto.',
    proof: 'Software, automação, ChatBô e GeoAura formam uma base integrada para criar, operar e tornar a solução encontrável por pessoas e mecanismos de IA.',
    image: '/brand/tironi-symbol.png', imageAlt: 'Desenvolvimento de soluções com inteligência artificial', process: commonProcess,
    faqs: [['Vocês trabalham com RAG?', 'Sim. A arquitetura inclui fontes, segmentação, busca, permissões, citações e avaliação.'], ['Qual modelo de IA é usado?', 'A escolha depende de qualidade, latência, custo, privacidade e portabilidade exigidos pelo caso.'], ['A solução pode evoluir?', 'Sim. Monitoramento e arquitetura modular permitem corrigir dados, prompts, fluxos, ferramentas e modelos.']],
  },
];

export const getServiceLandingPage = (slug) => serviceLandingPages.find((page) => page.slug === slug);
export { whatsapp as serviceLandingWhatsApp };
